### ISSUE TITLE
software bug the job has benn created but the operations status nerver been updated

### ISSUE THREAD

**Issue by cleverhu** [kubean-io/kubean#102]
**Describe the version**
version about:
1. kubean
2. kubespray
3. kubenetes
4. what CNI and itsversion

**Describe the bug**
batch-add-nodes-lwn2j-job" already exists
W0902 07:50:20.264803       1 controller.go:427] create job kpanda-calico-ops-batch-add-nodes-lwn2j-job for kuBeanClusterOp kpanda-calico-ops-batch-add-nodes-lwn2j
E0902 07:50:20.273289       1 controller.go:285] jobs.batch "kubean-kpanda-calico-ops-batch-add-nodes-lwn2j-job" already exists
W0902 07:50:21.847108       1 controller.go:427] create job kpanda-calico-ops-batch-add-nodes-lwn2j-job for kuBeanClusterOp kpanda-calico-ops-batch-add-nodes-lwn2j
E0902 07:50:21.855365       1 controller.go:285] jobs.batch "kubean-kpanda-calico-ops-batch-add-nodes-lwn2j-job" already exists
W0902 07:50:23.663799       1 controller.go:119] Delete KuBeanClusterOps: name: kpanda-calico-ops-create-cluster-pw2cw, createTime: 2022-08-31 06:20:00 +0000 UTC
W0902 07:50:24.651101       1 controller.go:427] create job kpanda-calico-ops-batch-add-nodes-lwn2j-job for kuBeanClusterOp kpanda-calico-ops-batch-add-nodes-lwn2j
E0902 07:50:24.666193       1 controller.go:285] jobs.batch "kubean-kpanda-calico-ops-batch-add-nodes-lwn2j-job" already exists
W0902 07:50:30.242196       1 controller.go:427] create job kpanda-calico-ops-batch-add-nodes-lwn2j-job for kuBeanClusterOp kpanda-calico-ops-batch-add-nodes-lwn2j
E0902 07:50:30.249527       1 controller.go:285] jobs.batch "kubean-kpanda-calico-ops-batch-add-nodes-lwn2j-job" already exists
W0902 07:50:32.218333       1 controller.go:96] update cluster kpanda-calico status.condition
W0902 07:50:40.867012       1 controller.go:427] create job kpanda-calico-ops-batch-add-nodes-lwn2j-job for kuBeanClusterOp kpanda-calico-ops-batch-add-nodes-lwn2j
E0902 07:50:40.900049       1 controller.go:285] jobs.batch "kubean-kpanda-calico-ops-batch-add-nodes-lwn2j-job" already exists
W0902 07:51:01.657133       1 controller.go:427] create job kpanda-calico-ops-batch-add-nodes-lwn2j-job for kuBeanClusterOp kpanda-calico-ops-batch-add-nodes-lwn2j
E0902 07:51:01.678211       1 controller.go:285] jobs.batch "kubean-kpanda-calico-ops-batch-add-nodes-lwn2j-job" already exists
W0902 07:51:42.847353       1 controller.go:427] create job kpanda-calico-ops-batch-add-nodes-lwn2j-job for kuBeanClusterOp kpanda-calico-ops-batch-add-nodes-lwn2j
E0902 07:51:42.872416       1 controller.go:285] jobs.batch "kubean-kpanda-calico-ops-batch-add-nodes-lwn2j-job" already exists
W0902 07:53:05.043479       1 controller.go:427] create job kpanda-calico-ops-batch-add-nodes-lwn2j-job for kuBeanClusterOp kpanda-calico-ops-batch-add-nodes-lwn2j
E0902 07:53:05.072472       1 controller.go:285] jobs.batch "kubean-kpanda-calico-ops-batch-add-nodes-lwn2j-job" already exists
W0902 07:55:49.239901       1 controller.go:427] create job kpanda-calico-ops-batch-add-nodes-lwn2j-job for kuBeanClusterOp kpanda-calico-ops-batch-add-nodes-lwn2j
E0902 07:55:49.269505       1 controller.go:285] jobs.batch "kubean-kpanda-calico-ops-batch-add-nodes-lwn2j-job" already exists

**How To Reproduce**
Steps to reproduce the issue:

**Expected behavior**
update the operations status

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.
<img width="970" alt="企业微信截图_71b89759-cb6d-4ce0-837e-9bd6dec541f2" src="https://user-images.githubusercontent.com/51436614/188094337-9bed5ddb-aae3-4670-85e6-a1a308634926.png">

**Additional context**

**Comment by hangscer8** [comment]
fix in #113 
https://github.com/kubean-io/kubean/pull/113/files#diff-dff1bd047861717411b5249b25bf3cba4278d8821051f305ca25d29efbf47c49R417
