### ISSUE TITLE
Optimize gather facts execution time

### ISSUE THREAD

**Issue by ErikJiang** [kubean-io/kubean#1049]
In the existing playbook to gather facts data, all the data is gathered, which causes a certain degree of time-consuming situation, we should get a limited fact subset, so as to improve the execution efficiency.

**Comment by ErikJiang** [comment]
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html#parameter-gather_subset

**Comment by tu1h** [comment]
improved by https://github.com/kubean-io/kubean/pull/1076/files#diff-9864c355f2595089183328d45da2d99c2b0d6802d78b1d58f8879b1c47aa227dR17-R21
