### ISSUE TITLE
documentation issue: no content in Usage

### ISSUE THREAD

**Issue by tukwila** [kubean-io/kubean#11]
**Documentation issue**
1. miss documentation

In README.md, there is no any content in Usage chapter:
<img width="790" alt="企业微信截图_26922772-a90d-4236-8308-677df3a86b99" src="https://user-images.githubusercontent.com/13757056/180112927-f4ac0881-273d-4761-9771-cf5f4e37821c.png">

**Comment by ErikJiang** [comment]
Documentation has been updated:
https://github.com/kubean-io/kubean#quick-start
