### ISSUE TITLE
add node, clusteroperation success but failed to add node

### ISSUE THREAD

**Issue by KubeKyrie** [kubean-io/kubean#1123]
**Describe the version**
kubean v0.11.2

**Describe the bug**
add node, clusteroperation success but failed to add node

**How To Reproduce**
Steps to reproduce the issue:

**Expected behavior**

**Screenshots and log**
![image](https://github.com/kubean-io/kubean/assets/139965836/3bdaef81-adee-46b7-bd45-d51d800c36f6)

![image](https://github.com/kubean-io/kubean/assets/139965836/252fc200-90d5-4844-9da5-78ee58fac669)

actually failed to add the node hyw-test3

![image](https://github.com/kubean-io/kubean/assets/139965836/e744950e-0a41-4d62-afda-6234fb5d5441)

**Additional context**
the node to be added is vm cloned from worker node of another k8s cluster

**Comment by tu1h** [comment]
This may be because the node to be added to the cluster is impure. Maybe it has been already at a cluster.

**Comment by ErikJiang** [comment]
It is recommended to add a pre-check to scale.yml for Kubespray. If the node is already being used by another cluster, an error should be raised and the process should exit. If you are interested, you are welcome to contribute code to Kubespray.
