### ISSUE TITLE
Provision k8s cluster as well as provision some add-on or application 

### ISSUE THREAD

**Issue by panpan0000** [kubean-io/kubean#1151]
Standing on GitOps perspective ,  we can hold the cluster CR in git.
so that we can recreate a cluster easily.
but the helm charts (customized addon)  can not be included in kubean CR, so I will have to helm install after kubean provisioning.

**Comment by ErikJiang** [comment]
You can utilize the custom action feature to address the requirement of installing other Helm applications.
https://kubean-io.github.io/kubean/en/concepts/custom_action/
