### ISSUE TITLE
KuBeanClusterOps values should be validated

### ISSUE THREAD

**Issue by tukwila** [kubean-io/kubean#12]
**Describe the version**
version about:
1. kubean: v0.0.0
2. kubespray: master
3. kubenetes
4. what CNI and itsversion: not related

**Describe the bug**

In kubeanclusterops.yml, i input spec.image value as _ to check if such value can be created as one job, and job is created but pod was failed with error: 

Events:
  Type     Reason         Age                     From               Message
  ----     ------         ----                    ----               -------
  Normal   Scheduled      6m37s                   default-scheduler  Successfully assigned kubean-system/kubean-e2e-cluster1-install-1-job-dbl2b to kubean-v0.0.0-2-gd363e5dc-29681-host-control-plane
  Warning  Failed         4m28s (x12 over 6m36s)  kubelet            Error: InvalidImageName
  Warning  InspectFailed  96s (x25 over 6m36s)    kubelet            Failed to apply default image tag "\_": couldn't parse image reference "_": invalid reference format
so, i think kubeanclusterops should so some parameter check to prevent !@#$%^&*()-=_+<>/? such characters.
**How To Reproduce**
Steps to reproduce the issue:
set image: _ in kubeanclusterops.yml then apply it:
kubectl apply -f e2e-install-cluster --kubeconfig=$MAIN_KUBECONFIG --validate=false
**Expected behavior**
kubean should do some parameter check.
**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

**Additional context**

**Comment by ErikJiang** [comment]
@tukwila 你的意思是 kubectl apply kubeanxxx.yml 时，如果image不符合规范就应该apply失败，但目前kubean在日志中已经有相应提示 InvalidImageName，不确定 kubectl apply 是否可验证，据我所知，`kubectl create deploy  test --image=xxx` 镜像内容同样不规范，但可以创建成功，只是运行失败。

@hangscer8 你和 @tukwila  确认一下

**Comment by tukwila** [comment]
已确认：
在用户使用我们的安装包的场景下，不会出现这种error value的情况；此issue可关闭
