### ISSUE TITLE
create cluster in offline scene, encounter "the output has been hidden due...." 

### ISSUE THREAD

**Issue by issimo1** [kubean-io/kubean#1212]
Hello！Using kubean create cluster in offline scene, i encounter this error. The minio server is normal.
VarHostCm.yml:
![image](https://github.com/kubean-io/kubean/assets/68982219/afc068c3-074d-4872-97e3-4839ba174697)
ClusterOperation job logs:
![1714037151944](https://github.com/kubean-io/kubean/assets/68982219/2962fd41-ed66-4418-8404-7d8e31cd3316)
Minio server:
![image](https://github.com/kubean-io/kubean/assets/68982219/087aa2c2-7496-4cbd-bb54-099b776de913)

the url can download directly. can u help me?

**Comment by issimo1** [comment]
@ErikJiang please!

**Comment by tu1h** [comment]
Hi @issimo1, could you add `unsafe_show_logs: true` into airgap-vars-conf configmap to get the detail logs and run clusteroperation again?
In addition, you should replace `REGISTRY_HOST:REGISTRY_PORT` with correct value.

**Comment by issimo1** [comment]
TY! I changed the yml on test/common-offilne/var-host-cm.yml, it can pull images normally! but i encountered a new error，choose containerd as container-manager, should replace `- prefix: "registry_host_key"`?
![image](https://github.com/kubean-io/kubean/assets/68982219/4aa4ebf1-f2d4-446f-bf38-42080a2ca0d4)

**Comment by tu1h** [comment]
Right, `registry_host_key` should be replaced.
But `test/common-offilne/var-host-cm.yml` is only used for Kubean e2e test. In your case, you may use these files on https://github.com/kubean-io/kubean/tree/main/examples/install/3.airgap which are prepared for the experiencers.

**Comment by issimo1** [comment]
Thank u very much! but i use `examples/install/3.airgap`, it download `eg: kubeadm、kube_version etc` its version is latest! but `kubean/files-v0.14.0` is `v1.27.5`. So In `Var-host-cm.yml` need to specify version compaction minio file?

**Comment by tu1h** [comment]
In general, you just need to specify `kube_version: v1.27.5` in `Var-host-cm.yml`.

**Comment by issimo1** [comment]
Thanks, it can download each binaries. Use `airgap` In `TASK [download : Download | Download files / images]`  setup，this error is  common as use `test/common-offline/*.yml`,  `images_groups` should be specify?
![image](https://github.com/kubean-io/kubean/assets/68982219/749d29bf-2ee0-4851-8efc-60f8c3f2e41e)

![image](https://github.com/kubean-io/kubean/assets/68982219/4da78bb2-698c-4035-b6ed-33708eda397f)

**Comment by tu1h** [comment]
What's the version of spray-job in `ClusterOperation` CR?

**Comment by issimo1** [comment]
0.14.0，maybe try latest spray-job?

**Comment by tu1h** [comment]
There is a bug from upstream, see https://github.com/kubernetes-sigs/kubespray/pull/11105.
We are now at tag [v0.13.x](https://github.com/kubean-io/kubean/releases/tag/v0.13.11) instead of v0.14.x. Sorry for your time.

**Comment by issimo1** [comment]
NO PROBLEM！thank u solution my question patiently！more gracefully！

**Comment by issimo1** [comment]
Excuse me! I'm back. How to specify image version. The etcd version is `quay.io/coreos/etcd:v3.5.10`, but images version in `Harbor` is `v3.5.12` .Although I can push a `v3.5.10` version, I still hope that it can be automated like ` download_url: "quay.io/coreos/etcd:xxxx"`. have any way？
![image](https://github.com/kubean-io/kubean/assets/68982219/01a6a2d0-7640-43ed-b5e5-20bd3eb2045c)

**Comment by tu1h** [comment]
That is because the files/images you imported are v0.14.0, so re-import v0.13.11.

**Comment by issimo1** [comment]
yeah, I saw the images list diff. Thank you.
