### ISSUE TITLE
How to configure the host-cm.yml to create a cluster with one master and one slave

### ISSUE THREAD

**Issue by issimo1** [kubean-io/kubean#1214]
**usage issue**
1. doubts about how to use the software
Hi ! 
I want to create a cluster with one master and one slave. How should I configure the `host-cm.yml`?
![image](https://github.com/kubean-io/kubean/assets/68982219/bc8c6dcb-276e-49f8-b73c-9c72db3acc7c)

Thanks !

**Comment by ErikJiang** [comment]
I recommend you read the documentation on inventory in kubespray first. It will help you understand how to configure it.

https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ansible.md#inventory

**Comment by issimo1** [comment]
Thanks ! I have a question about i want to use `kubean` create a cluster, which version is specify `1.22.x`. And which version kubean can support?

**Comment by ErikJiang** [comment]
For example, if you want to know the Kubernetes version range supported by kubean version v0.13.11, you can query it using the following URL.
https://github.com/kubean-io/kubean-helm-chart/blob/kubean-v0.13.11/charts/kubean/templates/manifest.cr.yaml#L77-L96
