### ISSUE TITLE
Kubean v0.2.1 is not supported installing ARM arch kubernetes? 

### ISSUE THREAD

**Issue by issimo1** [kubean-io/kubean#1261]
**usage issue**
1. doubts about how to use the software
Hello ErikJiang,
I want to konw the Kubean v0.2.1 is not supported installing  kubernetes in ARM arch? The kubean version v0.2.1 Release can not supply the os-pkgs and image_pkgs of the arm. If supported ARM  only replace amd64 install package files of os-pkgs same version?

**Comment by ErikJiang** [comment]
I'm curious why you chose an early version of kubean. Was there a specific reason? You should know that early versions of kubean have very limited, or even no, support for offline scenarios. If you want to deploy an ARM-based cluster, you should use a more recent higher version.

**Comment by issimo1** [comment]
Thank you for your response. Due to project requirements, I must use `K8s v1.22`, and only `Kubean v0.2.1` supports this. It worked when I tried it on a Debian system. However, since version 0.2.1 does not provide ARM architecture images, I had to download a separate one. Now, the issue is that I cannot combine them into a single manifests file, hence this confusion.

**Comment by ErikJiang** [comment]
I roughly understand your requirements. In fact, kubean has already considered the deployment management needs of customers with low-version Kubernetes clusters, but it currently only supports the minimum version of v1.23.0, and users need to manually build the offline package through the airgap-patch image. The support for backward compatible versions can be referred to at: https://kubean-io.github.io/kubean/en/releases/artifacts/.
