### ISSUE TITLE
feature: after a cluster is created by kubean, we hope the helm tool can be installed on master node 

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#129]
**1 Code requirement**

as title

**Comment by ErikJiang** [comment]
kubespray comes with the deployment capability of helm, which can be verified by the following parameters:
``` yaml
helm_version: v3.8.2
helm_enabled: true
```

**Comment by wenting-guo** [comment]
Test statement:
1. set paramater:  helm_enabled: true 
2. use ssh auth type: private key file

Test result:
after cluster crated, the helm tool is installed successfully

Be careful: 
if  sshpass is not installed on cluster nodes, and use user/password authorization mode，helm installation will fail.
