### ISSUE TITLE
software bug: too excessive clusterrole privilege

### ISSUE THREAD

**Issue by tu1h** [kubean-io/kubean#1326]
**Describe the version**
version about:
1. kubean `any`

**Describe the bug**
Permissions from https://github.com/kubean-io/kubean/blob/main/charts/kubean/templates/clusterrole.yaml are too loose. 

That may leads to malicious one can access the worker node which has deployments of Kubean, he/she can abuse these excessive permissions to do whatever he/she likes to the whole cluster.

Thanks for the @younaman(yang9467@umn.edu)'s reporting

**Expected behavior**
The Kubean should use accurate verbs and resource types to restrain the permission that granted to the deployment.

**Comment by younaman** [comment]
Dear kubean maintainers:
I am Nanzi Yang, thank you again for opening this issue. I will try my best to help you to review the permission set and enhance the permission set, other details are sent by an private email:)

Regards,
Nanzi Yang
