### ISSUE TITLE
ubuntu 22.04 LTS: software package seems to be missing

### ISSUE THREAD

**Issue by san3Xian** [kubean-io/kubean#1332]
![image](https://github.com/user-attachments/assets/f6dfc5c6-7160-4343-828d-66a2db9323ac)
![image](https://github.com/user-attachments/assets/549393ff-2c70-4340-9c6c-c6209be29ce3)

Even though I can see the deb package for ipset in the os-pkgs file, I still can't do apt search ipset or apt install `ipset`. It will break the k8s cluster installation. 
os-pkgs version: os-pkgs-ubuntu2204-v0.17.4.tar.gz

**Comment by ErikJiang** [comment]
I conducted relevant tests, but did not find the problem you mentioned, `ipset` can be recognized by apt package manager normally.

![image](https://github.com/user-attachments/assets/e46c043e-7270-480c-84d8-94f4c9098d28)
