### ISSUE TITLE
ubuntu 22 系统未安装 kernel unattended-upgrades 提示 /etc/apt/apt.conf.d/50unattended-upgrades does not exist 

### ISSUE THREAD

**Issue by mrligoog** [kubean-io/kubean#1356]
kubean:v0.17.5 
ubuntu 22 

**Describe the bug**
系统未安装 unattended-upgrades，提示缺少文件  /etc/apt/apt.conf.d/50unattended-upgrades does not exist 

![img_v3_02eb_86db8470-fd4f-46f2-bde6-549b5f7cdffg](https://github.com/user-attachments/assets/fdd585fd-eea2-4e8d-9586-a7d6c77d99cd)

**How To Reproduce**
Steps to reproduce the issue:

touch /etc/apt/apt.conf.d/50unattended-upgrades

**Comment by ErikJiang** [comment]
By normal default, The ubuntu system will have unattended-upgrades installed by default, and kubean will also have this tool installed by default. Suppose this tool is not installed on your Ubuntu. In that case, it may indicate that some customization of the operating system environment has been performed in the early stage, in which case you will need to manually install it.
 
![image](https://github.com/user-attachments/assets/2ff6c9c9-01be-449e-b55b-e64a2bf348df)

**Comment by ErikJiang** [comment]
https://github.com/kubernetes-sigs/kubespray/pull/11479
