### ISSUE TITLE
 create cluster failed

### ISSUE THREAD

**Issue by FloatXD** [kubean-io/kubean#1365]
https://github.com/kubean-io/kubean/actions/runs/10774807097/job/29878011277
![img_v3_02ej_a9af4ac5-9ed0-4663-a618-2faca1d6d52g](https://github.com/user-attachments/assets/9c1487e1-5842-43bc-8b6a-ae6e11b661ac)

**Comment by ErikJiang** [comment]
Starting with kubean v0.19.0, centos 7 is no longer supported. If you need support, please use the older version, or switch your spray-job image to the corresponding older release version from the following page：

 https://kubean-io.github.io/kubean/en/releases/artifacts/
