### ISSUE TITLE
Use kubean to upgrade k8s version from 1.30.0 to 1.30.4, coredns upgrade failed

### ISSUE THREAD

**Issue by FloatXD** [kubean-io/kubean#1397]
CoreDNS will not be upgraded: start version '1.11.3' not supported

coredns_version: "{{ 'v1.11.3' if (kube_version is version('v1.30.0', '>=')) else 'v1.11.1' }}"

https://github.com/kubean-io/kubean/actions/runs/11685731860/job/32565500225

**Comment by ErikJiang** [comment]
https://github.com/kubernetes/kubernetes/pull/126797

**Comment by ErikJiang** [comment]
https://github.com/kubernetes-sigs/kubespray/pull/11691
