### ISSUE TITLE
software bug: during my installing k8s cluster procedure, kubean report error about copy task: [kubernetes-apps/helm : Helm | Copy helm binary from download dir]

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#141]
**Describe the version**
version about: 
1. kubean: v0.2.2
2. kubespray: latest
3. kubenetes: 1.24.4
4. what CNI and itsversion

**Describe the bug**
1. set config: helm_enabled=true
2. start install k8s cluster
3. it report: fatal: [master1]: FAILED! => {"changed": false, "cmd": "sshpass", "msg": "[Errno 2] No such file or directory", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

4. check the download file in kubeanOperator node:

![image](https://user-images.githubusercontent.com/99961476/190334860-143739a9-606e-47bc-94a6-1a7ca6122b6e.png)

5. login cluster master node, check cluster status: kubectl get node

![image](https://user-images.githubusercontent.com/99961476/190334672-7040bdeb-1d04-42fd-a155-e25ce044c0fb.png)

6.  install sshpass tool on master1, and manual pull helm file from kubeanOperator node:
  
![image](https://user-images.githubusercontent.com/99961476/190335277-65e642d6-9b7b-4a24-a801-9ab15f6251a3.png)

**How To Reproduce**
Steps to reproduce the issue:

**Expected behavior**

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

**Additional context**

**Comment by ErikJiang** [comment]
There are two ways to solve this problem:
1. Install `sshpass` on the target host
2. Ansible uses `private key mode` to access the target host instead of `username and password mode`

**Comment by hangscer8** [comment]
This is related to the mode of synchronize file.

**Comment by hangscer8** [comment]
It is realted with https://github.com/kubernetes-sigs/kubespray/pull/9343
