### ISSUE TITLE
operator image can't be pulled successfully

### ISSUE THREAD

**Issue by cleverhu** [kubean-io/kubean#162]
**Describe the version**
version about:
1. kubean
2. kubespray
3. kubenetes
4. what CNI and itsversion

**Describe the bug**
The image ` ghcr.io/kubean-io/kubean-operator:v0.2.5` can't be pulled in local.

**How To Reproduce**
Steps to reproduce the issue:
Install by helm chart.

**Expected behavior**
The image should be pulled successfully.
We should use image registry to speed up.

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

**Additional context**

**Comment by wenting-guo** [comment]
i  meet this problem also in 0.2.7

**Comment by ErikJiang** [comment]
It is not recommended to use the proxy registry to speed up, the proxy has a synchronization delay problem, there will be pull failure, if you want to use the proxy image address, you can specify through helm's `--set` parameter

**Comment by hangscer8** [comment]
` --set image.repository=ghcr.m.daocloud.io/kubean-io/kubean-operator` to speedup pulling image
