### ISSUE TITLE
the kubean version in KubeanInfoManifest is wrong

### ISSUE THREAD

**Issue by cleverhu** [kubean-io/kubean#163]
**Describe the version**
version about:
1. kubean
2. kubespray
3. kubenetes
4. what CNI and itsversion

**Describe the bug**
The version of kubean has benn upgraded to 0.2.5, howerver, the version in KubeanInfoManifest is still 0.2.4.

**How To Reproduce**
Steps to reproduce the issue:
Install kubean 0.2.4 and upgrade it to 0.2.5.

**Expected behavior**

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

**Additional context**

**Comment by hangscer8** [comment]
need to test

**Comment by hangscer8** [comment]
This is related to #181

**Comment by hangscer8** [comment]
This is related to `Helm Upgrade`.

**Comment by hangscer8** [comment]
We modify the way how to install chrats in #190 .
