### ISSUE TITLE
software bug: PR CI result not correct

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#177]
**Describe the bug**
when e2e fail, the PR CI result is still success.

the 
https://github.com/kubean-io/kubean/actions/runs/3080169472
![image](https://user-images.githubusercontent.com/99961476/192947450-7dca6968-2e68-4365-bb9a-9047da0002b1.png)

**Expected behavior**
the summary result should correctly show the pipeline steps result: when e2e fail, the summary result should be fail

**Comment by hangscer8** [comment]
the PR CI result should be failed when e2e test is failed.

**Comment by tukwila** [comment]
Contact with reporter that this issue is to be observation.
