### ISSUE TITLE
coredns upstream config not allow blank

### ISSUE THREAD

**Issue by panpan0000** [kubean-io/kubean#178]
when no nameserver filled in host machines' /etc/resolv.conf
coredns will fail to boot up with error `plugin/forward: no nameservers found`

I guess sth wrong in coredns config 

kubectl edit configmap coredns -n kube-system

```
        forward . /etc/resolv.conf {
          prefer_udp
          max_concurrent 1000
        }
```

**Comment by yankay** [comment]
The coredns has the same issue.

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/coredns/coredns.yaml.in#L83
