### ISSUE TITLE
documentation issue

### ISSUE THREAD

**Issue by yulng** [kubean-io/kubean#179]
Create a cluster using a clean virtual machine,report errors
![image](https://user-images.githubusercontent.com/31728060/192955137-0ab18b18-ad45-4070-8745-dad5ea95c89b.png)
![image](https://user-images.githubusercontent.com/31728060/192955155-98cdffbc-ac34-417c-bd0f-3919559b99c7.png)

**Comment by wenting-guo** [comment]
please supply more info, such as the creation log

**Comment by wenting-guo** [comment]
no details to debug, close it
