### ISSUE TITLE
CI failure: there is a certain probability that kubean helm charts install fail cause' cr installed before api/chart/_crds

### ISSUE THREAD

**Issue by tukwila** [kubean-io/kubean#181]
Set title to be in the format CI: <test-name>.

Copy-paste the output the test failure.
<img width="690" alt="企业微信截图_d2bb66f7-7b03-4820-8a56-8e85ce151ee2" src="https://user-images.githubusercontent.com/13757056/193077888-91d7ac2d-4407-4f43-8587-bde903f42626.png">

refer to E2E CI: https://github.com/kubean-io/kubean/actions/runs/3148878224/jobs/5127482268

**Comment by hangscer8** [comment]
need to fix `_crds` in charts
