### ISSUE TITLE
Declare the KubeSpray version in the Code

### ISSUE THREAD

**Issue by yankay** [kubean-io/kubean#183]
The KubeSpray version now for kubean is dynamic, it changed in CI.

The KubeSpray it an important dependency for the kubean.

Should we declare it at the code like go mod ?

**Comment by ErikJiang** [comment]
https://github.com/kubean-io/kubean-helm-chart/blob/main/charts/kubean/templates/manifest.cr.yaml

Declared in manifest CR.
