### ISSUE TITLE
when ops is created, some key value such as namespace/name is better to validate if they are matched

### ISSUE THREAD

**Issue by tukwila** [kubean-io/kubean#19]
In KuBeanClusterOps, there are some important keys between 4 yml files; such as:

1. In kubeanCluster.ymlm spec.hostsConfRef.namespace should be the same as metadata.namespace in hosts-conf-cm.yml
2. In kubeanCluster.ymlm spec.hostsConfRef.name should be the same as metadata.name in hosts-conf-cm.yml

**Comment by ErikJiang** [comment]
<img width="286" alt="image" src="https://user-images.githubusercontent.com/10629406/184568989-c43d4b1b-7dc8-4eec-90a8-6d85a16dadac.png">
Ref 当中的 namespace 需要用户设置，并确保该 ns 内，存在上述 cm or secret, kubean 能够做的就是当读取 ns 内没有这些资源时，在日志中报错提示

@tukwila

**Comment by hangscer8** [comment]
add check : hostsConfRef.namespace == varsConfRef.namespace ,in  the same namespace
