### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by ErikJiang** [kubean-io/kubean#202]
https://github.com/kubean-io/kubean/actions/runs/3248054947.

Copy-paste the output the test failure.
![image](https://user-images.githubusercontent.com/10629406/195784319-3299caf9-3587-4a37-b617-57aa10dc59da.png)

#### Explore new optimizations to replace set-output.

Upload the zip file generated from that test failure.

Copy-paste the link of the CI build where that test failure has happen.

Include any output from logs that you think may be relevant (to ease GitHub searches).
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands
```

**Comment by YunShiHang** [comment]
get
