### ISSUE TITLE
bug/feature: remove the kubeconf from crd kubeanclusterops.kubean.io

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#205]
according to code:
![企业微信截图_12b66ca4-0601-44ad-b1ce-1ba78a27cc65](https://user-images.githubusercontent.com/99961476/196103635-f455152c-cc4b-4483-9fd8-2f2ec0b14bd9.png)
i attempt to get kubeconfig from clusterops.status.kubeconf, but the kubeconf is not exists.
so, please check whether the kubeconf should be remove from crd kubeanclusterops.kubean.io

**Comment by hangscer8** [comment]
fix in #219
