### ISSUE TITLE
usage issue

### ISSUE THREAD

**Issue by tukwila** [kubean-io/kubean#21]
When i create one KuBeanClusterOps with some incorrect values, such ops status is as following:
  action: ""
  digest: 92df34c6021b9e5c38ef756fc79a988f
  status: ""
Now, i don't know how about this ops's process or status. Then i create anther ops again then i check the second ops status is :
status:
  action: ""
  digest: aada123ae06c2bed942d9a5861056328
  status: Blocked
and the logs:
I0722 03:38:00.030160       1 controller.go:238] clusterOps e2e-cluster1-install-2 is blocked and waiting for other clusterOps completed
so, i guess the first ops is in the endless loop; Can we mark the first ops as status:"Failed" and to do the second ops?

**Comment by hangscer8** [comment]
check: 
* image not exists
* preHook or postHook wrong args 
* action wrong args

**Comment by hangscer8** [comment]
#12 the same
