### ISSUE TITLE
the kubeconf context/cluster name should have  diff name among diff cluster instance

### ISSUE THREAD

**Issue by panpan0000** [kubean-io/kubean#235]
**Describe the version**
version about:
1. kubean v0.3.3 
2. kubespray
3. kubenetes 
4. what CNI and itsversion

**Describe the bug**

`kubectl -n kubean-system get cm ${clusterName}-kubeconf`

When kubean provision >= 2 clusters,  all of their kubeconf use the same context , usrname and cluster name :

cluster: `cluster: cluster.local`
context: `  name: kubernetes-admin@cluster.local`
user: `kubernetes-admin`

it should be named as cluster name

**Comment by hangscer8** [comment]
I will fix it
