### ISSUE TITLE
software bug：push images to registry fail during the offline install.

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#246]
**Describe the version**
version about:
1. kubean  v0.3.3

**Describe the bug**
registry version: 2.8.1, 2,
registry run command: docker run -d -p 5000:5000 --restart always --name registry registry:2.8.1

//I replaced the follew registry_address to my actual address
import command: DEST_TLS_VERIFY=false ./import_images.sh ${registry_address}  
![image](https://user-images.githubusercontent.com/99961476/197753037-96959c7a-39e7-4605-8a8b-bc2a841d5462.png)

when replace the registry images to version 2.6.2, the import step  will success

**How To Reproduce**
Steps to reproduce the issue:

**Expected behavior**
all the images can import to registry

**Comment by wenting-guo** [comment]
@hangscer8

**Comment by wenting-guo** [comment]
should   mention recommend registry version is :2.6.2

**Comment by hangscer8** [comment]
Please use docker regsitry `2.6.2`
