### ISSUE TITLE
How does creation and update preserve the previous cluster configuration

### ISSUE THREAD

**Issue by yanrongshi** [kubean-io/kubean#252]
**usage issue**
1. When kubean creates k8s cluster, kunernetes and system parameters are configured. If the user manually modifies the related parameters after the cluster is created, the configuration is inconsistent. How to solve this problem?
2. A follow-up question is whether kubean rewrites manually modified kubernetes and kernel parameters into kubean configuration parameters when new nodes are added or the cluster is upgraded

**Comment by wenting-guo** [comment]
@ErikJiang
