### ISSUE TITLE
software bug：create a cluster after reset, will fail

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#295]
**Describe the version**
version about:
1. kubean: v0.4.2-rc2

**Describe the bug**
1. create a cluster
2. reset cluster
3. set override_system_hostname：false, and install cluster
4. the creation will fail 

**Screenshots and log**
![image](https://user-images.githubusercontent.com/99961476/200812931-44eabc31-e3f0-4151-9490-85efce9a6896.png)

If applicable, add screenshots and log to help explain your problem.

TASK [kubernetes/control-plane : kubeadm | Create kubeadm config] **************
changed: [node1]
Wednesday 09 November 2022  10:16:28 +0000 (0:00:02.474)       0:16:30.397 **** 
Wednesday 09 November 2022  10:16:28 +0000 (0:00:00.060)       0:16:30.458 **** 
Wednesday 09 November 2022  10:16:28 +0000 (0:00:00.061)       0:16:30.520 **** 
Wednesday 09 November 2022  10:16:28 +0000 (0:00:00.049)       0:16:30.569 **** 
Wednesday 09 November 2022  10:16:28 +0000 (0:00:00.061)       0:16:30.631 **** 
Wednesday 09 November 2022  10:16:28 +0000 (0:00:00.068)       0:16:30.699 **** 
Wednesday 09 November 2022  10:16:28 +0000 (0:00:00.059)       0:16:30.758 **** 
Wednesday 09 November 2022  10:16:28 +0000 (0:00:00.056)       0:16:30.815 **** 
Wednesday 09 November 2022  10:16:29 +0000 (0:00:00.060)       0:16:30.875 **** 
FAILED - RETRYING: [node1]: kubeadm | Initialize first master (3 retries left).
FAILED - RETRYING: [node1]: kubeadm | Initialize first master (2 retries left).
FAILED - RETRYING: [node1]: kubeadm | Initialize first master (1 retries left).

TASK [kubernetes/control-plane : kubeadm | Initialize first master] ************
fatal: [node1]: FAILED! => {"attempts": 3, "changed": true, "cmd": ["timeout", "-k", "300s", "300s", "/usr/local/bin/kubeadm", "init", "--config=/etc/kubernetes/kubeadm-config.yaml", "--ignore-preflight-errors=all", "--skip-phases=addon/coredns", "--upload-certs"], "delta": "0:05:00.030700", "end": "2022-11-09 10:36:51.106676", "failed_when_result": true, "msg": "non-zero return code", "rc": 124, "start": "2022-11-09 10:31:51.075976", "stderr": "W1109 10:31:51.301104   18010 utils.go:69] The recommended value for \"clusterDNS\" in \"KubeletConfiguration\" is: [10.96.0.10]; the provided value is: [10.96.0.3]\n\t[WARNING Hostname]: hostname \"node1\" could not be reached\n\t[WARNING Hostname]: hostname \"node1\": lookup node1 on 10.0.2.3:53: no such host", "stderr_lines": ["W1109 10:31:51.301104   18010 utils.go:69] The recommended value for \"clusterDNS\" in \"KubeletConfiguration\" is: [10.96.0.10]; the provided value is: [10.96.0.3]", "\t[WARNING Hostname]: hostname \"node1\" could not be reached", "\t[WARNING Hostname]: hostname \"node1\": lookup node1 on 10.0.2.3:53: no such host"], "stdout": "[init] Using Kubernetes version: v1.23.7\n[preflight] Running pre-flight checks\n[preflight] Pulling images required for setting up a Kubernetes cluster\n[preflight] This might take a minute or two, depending on the speed of your internet connection\n[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'", "stdout_lines": ["[init] Using Kubernetes version: v1.23.7", "[preflight] Running pre-flight checks", "[preflight] Pulling images required for setting up a Kubernetes cluster", "[preflight] This might take a minute or two, depending on the speed of your internet connection", "[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'"]}

NO MORE HOSTS LEFT *************************************************************

**Comment by tu1h** [comment]
I did not reproduce after trying many times
