### ISSUE TITLE
After arm K8s installation is complete， kube-apiserver logs "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by dasu23** [kubean-io/kubean#319]
use demo-dev kpanda-cilium-14：kubean 0.3.2

kube version：
`Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", , GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/arm64"}`

containerd version：
`containerd github.com/containerd/containerd v1.6.8 `

logs info：
kubectl logs -n kube-system kube-apiserver-k8s-master
`"Unable to authenticate the request" err="[x509: certificate signed by unknown authority, verifying certificate SN=680443660627050067, SKID=, AKID=50:7F:D5:76:6A:26:55:96:19:85:13:F2:07:A7:1F:01:03:A8:A7:A6 failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kubernetes\")]"`

![image](https://user-images.githubusercontent.com/28703662/202597426-24881427-5477-45cf-ab76-1b59ef7a478e.png)

**Comment by ErikJiang** [comment]
1. Please provide more complete logs, such as kubelet logs
2. Check whether the NTP of the node is synchronized
3. You can try to reset the cluster and redeploy it. Before that, please ensure that the node NTP are synchronized

**Comment by wenting-guo** [comment]
arm cluster is ok now
