### ISSUE TITLE
kubernetes version supports mode optimization

### ISSUE THREAD

**Issue by yanrongshi** [kubean-io/kubean#346]
**usage issue**
The current kubean follows the main branch of kubesprey, and the main branch of kubespray follows kubernetes, which only supports 3 version range kubernetes clusters. For example, the latest version of kubean only supports three version ranges of 1.25, 1.24, and 1.23. If I need to use the latest version of kubean to create a kubernetes cluster outside this version range, what should I do? Download an older version of kubean? obviously it doesn't make sense

**Comment by hangscer8** [comment]
if want to support the other k8s version apart from the supported version of the current kubean, We need use a kubean  of an other version.
