### ISSUE TITLE
Is it possible to create an ARM machine using an X86 management cluster

### ISSUE THREAD

**Issue by yanrongshi** [kubean-io/kubean#352]
Is it possible to create an ARM machine using an X86 management cluster

**Comment by hangscer8** [comment]
是的可以的。
如果是在线环境，则镜像和相关二进制都是在线获取，kubean会自动根据机器平台信息选择合适的版本。
如果是离线环境，则需要确保minio和regsitry里真的存在适合ARM平台的软件版本
