### ISSUE TITLE
feature: the document of offline usage, when create the llinux yum repo， the relation of steps is not clear

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#354]
文档： https://github.com/kubean-io/kubean/blob/main/docs/zh/offline.md
优化的地方：
1.  “1.1. 建立在线 ISO 镜像源” 和“1. 建立本地 ISO 镜像源” 是或的关系。只需要执行其中一个步骤就可以了。
2. 需要说明建立本地镜像源的时候需要在每个创建k8s集群的节点上执行

![image](https://user-images.githubusercontent.com/99961476/204427985-0dce7464-8cf2-4763-af17-b15bd030f7b8.png)

**Comment by hangscer8** [comment]
need update the doc
