### ISSUE TITLE
documentation issue：the extra softeware repo not only support centos, the more accurate state is: redaht os family

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#360]
there are several places can be updated:

(https://github.com/kubean-io/kubean/blob/main/docs/zh/offline.md)

![wecom-temp-1c0306e235d2e54d36c49ee2015f0264](https://user-images.githubusercontent.com/99961476/204475856-ea0f33f8-89fe-47ff-8a28-1732758ad129.png)

**Comment by yulng** [comment]
文件名已改为 airgap.md
