### ISSUE TITLE
feature：automatically set the spray-job image version, when the image tag is empty

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#363]
what need to do:
1. update the sample https://github.com/kubean-io/kubean/blob/main/artifacts/demo/kubeanClusterOps.yml:
change  "image: ghcr.m.daocloud.io/kubean-io/spray-job:latest" to " image: ghcr.m.daocloud.io/kubean-io/spray-job"
(maybe some other demo files will also be changed)

2. state the mechanism to user：when the spray-job image's tag is empty, kuebean will set the spray-job tag to same value of the kubean-operator tag

3. optimize the kubean code to achieve this function

**Comment by hangscer8** [comment]
need optimize the kubean-operator
