### ISSUE TITLE
There is no recommended kernel version for kubean

### ISSUE THREAD

**Issue by yanrongshi** [kubean-io/kubean#364]
There is no recommended kernel version for kubean

**Comment by ErikJiang** [comment]
kubernetes itself does not have a version limit on the kernel, but its underlying containers have related requirements.
1. [contained](https://github.com/containerd/containerd/blob/main/README.md#runtime-requirements) requires kernel version 4.x or higher
2. [docker](https://docs.docker.com/engine/install/binaries/#prerequisites) requires a minimum kernel version of 3.10

In addition, support for [linux cgroup v2](https://kubernetes.io/docs/concepts/architecture/cgroups/#requirements) requires a kernel version of at least 5.8.
