### ISSUE TITLE
Question: What is the difference with the cluster-api?

### ISSUE THREAD

**Issue by chaunceyjiang** [kubean-io/kubean#373]
I see this sentence `kubean is a cluster lifecycle management tool` in the document. 
I have a question. What is the difference between kubean and [clutser-api](https://github.com/kubernetes-sigs/cluster-api)?

**Comment by ErikJiang** [comment]
https://kubean-io.github.io/kubean/en/concepts/comparisons/

Based on kubespray, kubean does not have the complex CRD design of cluster-api, kubean aims to simplify the deployment of kubespray under container services
