### ISSUE TITLE
ubuntu kubean install failed

### ISSUE THREAD

**Issue by yulng** [kubean-io/kubean#383]
[evn]10.6.214.23
yml files: /root/ubuntuyw
ubuntu vm:10.6.158.59/58
Ubuntu 22.04.1 LTS \n \l
Linux master1 5.15.0-47-generic

step:
1 10.6.214.23的/root/下执行 kubectl apply -f ./ubuntuyw

2 report error
![企业微信截图_53aaeab8-f33c-4002-8800-b5cd377d9edd](https://user-images.githubusercontent.com/31728060/206134024-4530a154-7846-48f0-9f8c-ae2864337164.png)

**Comment by ErikJiang** [comment]
unrepeatable
