### ISSUE TITLE
During cluster upgrade, the job disappears for unknown reasons. Procedure

### ISSUE THREAD

**Issue by yanrongshi** [kubean-io/kubean#402]
During cluster upgrade, the job disappears for unknown reasons. Procedure

<img width="1401" alt="企业微信截图_ff6b891b-7366-4b4f-8ae3-52bfb58ddc07" src="https://user-images.githubusercontent.com/29862632/207881698-d3776099-803e-46f6-8aee-9e1dbc28cfaa.png">

**Comment by yanrongshi** [comment]
PLEG

**Comment by ErikJiang** [comment]
Unreproducible problems.
