### ISSUE TITLE
software bug: when install a k8s in my offline kylin nodes, the installation fail 

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#414]
install k8 in kylin sp2 offline nodes,
version: v0.4.2-rc2
log:
TASK [kubernetes/control-plane : kubeadm | Create kubeadm config] **************
changed: [node1]
Thursday 22 December 2022  03:28:11 +0000 (0:00:07.565)       0:50:37.372 *****
Thursday 22 December 2022  03:28:11 +0000 (0:00:00.060)       0:50:37.433 *****
Thursday 22 December 2022  03:28:11 +0000 (0:00:00.070)       0:50:37.503 *****
Thursday 22 December 2022  03:28:11 +0000 (0:00:00.058)       0:50:37.562 *****
Thursday 22 December 2022  03:28:11 +0000 (0:00:00.059)       0:50:37.621 *****
Thursday 22 December 2022  03:28:11 +0000 (0:00:00.069)       0:50:37.691 *****
Thursday 22 December 2022  03:28:11 +0000 (0:00:00.049)       0:50:37.741 *****
Thursday 22 December 2022  03:28:11 +0000 (0:00:00.065)       0:50:37.806 *****
Thursday 22 December 2022  03:28:11 +0000 (0:00:00.074)       0:50:37.881 *****
FAILED - RETRYING: [node1]: kubeadm | Initialize first master (3 retries left).
FAILED - RETRYING: [node1]: kubeadm | Initialize first master (2 retries left).
FAILED - RETRYING: [node1]: kubeadm | Initialize first master (1 retries left).

TASK [kubernetes/control-plane : kubeadm | Initialize first master] ************
fatal: [node1]: FAILED! => {"attempts": 3, "changed": true, "cmd": ["timeout", "-k", "300s", "300s", "/usr/local/bin/kubeadm", "init", "--config=/etc/kubernetes/kubeadm-config.yaml", "--ignore-preflight-errors=all", "--skip-phases=addon/coredns", "--upload-certs"], "delta": "0:05:00.003571", "end": "2022-12-22 11:48:47.375066", "failed_when_result": true, "msg": "non-zero return code", "rc": 124, "start": "2022-12-22 11:43:47.371495", "stderr": "W1222 11:43:47.401361   49193 utils.go:69] The recommended value for \"clusterDNS\" in \"KubeletConfiguration\" is: [10.96.0.10]; the provided value is: [10.96.0.3]", "stderr_lines": ["W1222 11:43:47.401361   49193 utils.go:69] The recommended value for \"clusterDNS\" in \"KubeletConfiguration\" is: [10.96.0.10]; the provided value is: [10.96.0.3]"], "stdout": "[init] Using Kubernetes version: v1.24.7\n[preflight] Running pre-flight checks\n[preflight] Pulling images required for setting up a Kubernetes cluster\n[preflight] This might take a minute or two, depending on the speed of your internet connection\n[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'", "stdout_lines": ["[init] Using Kubernetes version: v1.24.7", "[preflight] Running pre-flight checks", "[preflight] Pulling images required for setting up a Kubernetes cluster", "[preflight] This might take a minute or two, depending on the speed of your internet connection", "[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'"]}

**Comment by wenting-guo** [comment]
i meeted this phenomenon in also on centos nodes, after retry, it succeeded，but not sure they are same issue.

**Comment by tu1h** [comment]
When I watch the log of kubelet, can only find an error about `ca.crt`.
> node1 kubelet[44516]: Error: failed to construct kubelet dependencies: unable to load client CA file /etc/kubernetes/ssl/ca.crt: open /etc/kubernetes/ssl/ca.crt: no such file or directory

Then I retry `kubeadm init` manually, it passed.
> [bootstrap-token] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
> [bootstrap-token] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
> [bootstrap-token] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
> [kubelet-finalize] Updating "/etc/kubernetes/kubelet.conf" to point to a rotatable kubelet client certificate and key
> [addons] Applied essential addon: kube-proxy
> 
> Your Kubernetes control-plane has initialized successfully!
> 
> To start using your cluster, you need to run the following as a regular user:
> 
>  mkdir -p $HOME/.kube
>  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
>  sudo chown $(id -u):$(id -g) $HOME/.kube/config
> 
> Alternatively, if you are the root user, you can run:
> 
>   export KUBECONFIG=/etc/kubernetes/admin.conf
> 
> You should now deploy a pod network to the cluster.

**Comment by tu1h** [comment]
It seems like `kubeadm init` be coercive killed by the command `timeout -k 300s 300s ....`. When I run `kubeadm init`, it token 10 min about. So, it may a network problem.

I continued to follow up and found that pulling images took too long and occasionally failed.
![企业微信截图_16716909372796](https://user-images.githubusercontent.com/92532497/209089241-0efd805d-5b08-46e5-990d-9d379adb8daa.png)
![image](https://user-images.githubusercontent.com/92532497/209089774-0a7563cb-181e-4bef-a8ea-79222c8502fa.png)
