### ISSUE TITLE
feature: when set "override_system_hostname" to false, the k8s installation may fail

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#415]
set parameters:
override_system_hostname: false
container_manager: docker

the installation may fail sometimes
TASK [kubernetes/control-plane : kubeadm | Create kubeadm config] **************
changed: [node1]
Friday 09 December 2022  03:42:25 +0000 (0:00:02.765)       0:16:26.770 ******* 
Friday 09 December 2022  03:42:25 +0000 (0:00:00.066)       0:16:26.837 ******* 
Friday 09 December 2022  03:42:25 +0000 (0:00:00.057)       0:16:26.894 ******* 
Friday 09 December 2022  03:42:25 +0000 (0:00:00.062)       0:16:26.957 ******* 
Friday 09 December 2022  03:42:25 +0000 (0:00:00.074)       0:16:27.031 ******* 
Friday 09 December 2022  03:42:25 +0000 (0:00:00.082)       0:16:27.113 ******* 
Friday 09 December 2022  03:42:25 +0000 (0:00:00.071)       0:16:27.185 ******* 
Friday 09 December 2022  03:42:25 +0000 (0:00:00.073)       0:16:27.259 ******* 
Friday 09 December 2022  03:42:25 +0000 (0:00:00.072)       0:16:27.332 ******* 
FAILED - RETRYING: [node1]: kubeadm | Initialize first master (3 retries left).
FAILED - RETRYING: [node1]: kubeadm | Initialize first master (2 retries left).
FAILED - RETRYING: [node1]: kubeadm | Initialize first master (1 retries left).

TASK [kubernetes/control-plane : kubeadm | Initialize first master] ************
fatal: [node1]: FAILED! => {"attempts": 3, "changed": true, "cmd": ["timeout", "-k", "300s", "300s", "/usr/local/bin/kubeadm", "init", "--config=/etc/kubernetes/kubeadm-config.yaml", "--ignore-preflight-errors=all", "--skip-phases=addon/coredns", "--upload-certs"], "delta": "0:05:00.026421", "end": "2022-12-09 04:02:53.945480", "failed_when_result": true, "msg": "non-zero return code", "rc": 124, "start": "2022-12-09 03:57:53.919059", "stderr": "W1209 03:57:54.147933   25863 utils.go:69] The recommended value for \"clusterDNS\" in \"KubeletConfiguration\" is: [10.96.0.10]; the provided value is: [10.96.0.3]\n\t[WARNING Hostname]: hostname \"node1\" could not be reached\n\t[WARNING Hostname]: hostname \"node1\": lookup node1 on 10.0.2.3:53: no such host", "stderr_lines": ["W1209 03:57:54.147933   25863 utils.go:69] The recommended value for \"clusterDNS\" in \"KubeletConfiguration\" is: [10.96.0.10]; the provided value is: [10.96.0.3]", "\t[WARNING Hostname]: hostname \"node1\" could not be reached", "\t[WARNING Hostname]: hostname \"node1\": lookup node1 on 10.0.2.3:53: no such host"], "stdout": "[init] Using Kubernetes version: v1.23.7\n[preflight] Running pre-flight checks\n[preflight] Pulling images required for setting up a Kubernetes cluster\n[preflight] This might take a minute or two, depending on the speed of your internet connection\n[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'", "stdout_lines": ["[init] Using Kubernetes version: v1.23.7", "[preflight] Running pre-flight checks", "[preflight] Pulling images required for setting up a Kubernetes cluster", "[preflight] This might take a minute or two, depending on the speed of your internet connection", "[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'"]}

**Comment by wenting-guo** [comment]
need reproduction

**Comment by wenting-guo** [comment]
https://github.com/kubean-io/kubean/issues/415

**Comment by tu1h** [comment]
Seems like #295

**Comment by wenting-guo** [comment]
not happen for a long time, close it
