### ISSUE TITLE
Example Create cluster report Certificate 503

### ISSUE THREAD

**Issue by yanrongshi** [kubean-io/kubean#424]
<img width="1140" alt="企业微信截图_91d888c2-41ae-49f5-a760-efdd34bd4b27" src="https://user-images.githubusercontent.com/29862632/209745261-c8dd8fb9-b65f-4d4b-bc60-55d89f0ece94.png">
<img width="884" alt="企业微信截图_91446451-d273-45fc-99b9-4d2545ca7f2b" src="https://user-images.githubusercontent.com/29862632/209745273-f46fd4ad-36de-44b8-95fa-df361d23bb4e.png">

**Comment by ErikJiang** [comment]
The `containerd_insecure_registries` parameter needs to be set.
