### ISSUE TITLE
An offline installation uses an online source

### ISSUE THREAD

**Issue by yanrongshi** [kubean-io/kubean#428]
An offline installation uses an online source

![企业微信截图_326dcceb-845a-4d57-af02-aaaf5ba86213](https://user-images.githubusercontent.com/29862632/209746643-997c68b6-162f-4e29-bfff-9bbc6ce13c15.png)

**Comment by ErikJiang** [comment]
If installing in an offline environment, set the image to your registry address,  for example:
```
--set image.repository=temp.registry.io/ghcr.io/kubean-io/kubean-operator
--version=v0.4.2
```
