### ISSUE TITLE
The installation log is missing

### ISSUE THREAD

**Issue by cleverhu** [kubean-io/kubean#453]
**Describe the version**
version about:
1. kubean
v0.4.2-rc3-23-gfa9d3050
3. kubespray
4. kubenetes
v1.23.1
6. what CNI and itsversion

**Describe the bug**
Create a cluster by kubean. After 27 minutes, the logs disappear. Execute `kubectl logs - xxx - nkubean-system` to view there are no logs. The logs are retained for about 20 minutes.

**How To Reproduce**
Steps to reproduce the issue:

**Expected behavior**

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.
<img width="1290" alt="企业微信截图_f80a637c-7651-444e-b766-608aaa5db57f" src="https://user-images.githubusercontent.com/51436614/210502234-5aa218ae-0062-4963-b8aa-31a6e2f866de.png">

**Additional context**

**Comment by ErikJiang** [comment]
Problems that cannot be reproduced
