### ISSUE TITLE
CI failure: CD fail, after new tag created, the deployment step may fail

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#472]
**log**:
 https://github.com/kubean-io/kubean/actions/runs/3937005674

![image](https://user-images.githubusercontent.com/99961476/212855674-53c86adb-c979-4660-aba8-32fcbe66181d.png)

**Comment by hangscer8** [comment]
failed `cd` job : https://github.com/kubean-io/kubean/actions/runs/5070670067/jobs/9107189938

success `cd` job: https://github.com/kubean-io/kubean/actions/runs/5070670067/jobs/9117446467
