### ISSUE TITLE
software bug: offline install k8s on redhat7 and centos7 fail 

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#479]
**Describe the version**
version about:
1. kubean: v0.4.2-rc8

**Describe the bug**
create a k8s cluster on redhat7 os failed

**Screenshots and log**

https://github.com/kubean-io/kubean/actions/runs/3954897305/jobs/6772704767

![image](https://user-images.githubusercontent.com/99961476/213348718-b1019efe-07d2-4c08-ba9a-36c16b3ab64c.png)

TASK [container-engine/containerd : containerd | Copy containerd config file] ***
changed: [node2]
changed: [node1]
Thursday 19 January 2023  03:19:48 +0000 (0:00:01.075)       0:05:44.546 ****** 

TASK [container-engine/containerd : containerd ｜ Create registry directories] ***
fatal: [node1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'key'\n\nThe error appears to be in '/kubespray/roles/container-engine/containerd/tasks/main.yml': line 114, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: containerd ｜ Create registry directories\n  ^ here\n"}
fatal: [node2]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'key'\n\nThe error appears to be in '/kubespray/roles/container-engine/containerd/tasks/main.yml': line 114, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: containerd ｜ Create registry directories\n  ^ here\n"}

NO MORE HOSTS LEFT *************************************************************

**Comment by wenting-guo** [comment]
test on centos7 still fail

**Comment by tu1h** [comment]
Same problem mentioned at https://github.com/kubernetes-sigs/kubespray/pull/9566#issuecomment-1400139824 .
Tracking at https://github.com/kubernetes-sigs/kubespray/pull/9729

**Comment by wenting-guo** [comment]
https://github.com/kubernetes-sigs/kubespray/pull/9729 is merged, we need release a new version
