### ISSUE TITLE
software bug: create cluster with docker will case coredns pod blocked status

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#487]
**Describe the version**
version about:
1. kubean: v0.4.2-rc8
2. kubespray
3. kubenetes:v1.23.7
4. what CNI and itsversion: docker

**Describe the bug**
use docker as cni,  create a cluster the coredns and metrics-server pod will stay in  blocked status

**How To Reproduce**
set cni to docker

**Screenshots and log**
![image](https://user-images.githubusercontent.com/99961476/215934848-fcadaf60-f888-477c-adc3-eec84f990676.png)

![image](https://user-images.githubusercontent.com/99961476/215935113-cace0e5a-b400-4c0b-a574-dc8f764d510e.png)
![image](https://user-images.githubusercontent.com/99961476/215935646-90dab8ed-e386-4f37-8b25-61a090325be1.png)

**Additional context**

**Comment by wenting-guo** [comment]
when set k8s version to 1.24.7, use docker as cri, the cluster can be created successfully

**Comment by tu1h** [comment]
need use cri-dockerd 0.2.6 and below

**Comment by wenting-guo** [comment]
only version <= v0.4.2-rc8 has this problem, when use version <= v0.4.2-rc8 to install a k8s 1.23.7 , we need set the cri-docker version like below:

<img width="994" alt="企业微信截图_d2a0dd10-e5e6-4ec6-b5e5-4fd968af45d8" src="https://user-images.githubusercontent.com/99961476/217131567-bc94338f-df97-4ff1-a1e1-abe5ab5a02a1.png">
