### ISSUE TITLE
CI failure: V0.4.2-RC9 offline create cluster fail

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#495]
**envronment info**
kubean-version: v.4.2-rc9
k8s version:1.24.7
containerd version: 1.6.16
crictl version: 1.24.0
os: redhat7

**error msg**
![企业微信截图_063a6317-148f-4589-b92e-d0962032790d](https://user-images.githubusercontent.com/99961476/216530737-8d13ba54-0065-49d4-bf20-d0525aacff22.png)

**debug**
login the master node excute kubeadm: 
`/usr/local/bin/kubeadm  init  --config=/etc/kubernetes/kubeadm-config.yaml  --ignore-preflight-errors=all --skip-phases=addon/coredns  --upload-certs`
![企业微信截图_8605ba26-452f-4899-a5d4-b824b919734c](https://user-images.githubusercontent.com/99961476/216530764-2c1233fe-f495-41e0-a722-88bea8ebd289.png)

**Comment by tu1h** [comment]
Wait for https://github.com/kubernetes-sigs/kubespray/pull/9743

**Comment by yankay** [comment]
HI @tu1h , it has fixed.

**Comment by wenting-guo** [comment]
success ci recored of the new release: https://github.com/kubean-io/kubean/actions/runs/4182604509/jobs/7262679969
