### ISSUE TITLE
software bug:cluster that created by kubean can not delete resources

### ISSUE THREAD

**Issue by Penguin-zlh** [kubean-io/kubean#496]
**Describe the version**
version about:
1. kubean  kubean-v0.4.2-rc3
2. kubespray
3. kubenetes
4. what CNI and itsversion

**Describe the bug**
cluster that created by kubean can not delete resources

**How To Reproduce**
Steps to reproduce the issue:
**environment:offline environment**
create sts, waitting for running and then delete sts, check whether pod deleted

**Expected behavior**
sts, pod etc. can be deleted successfully

**Screenshots and log**
```
I0203 06:08:51.978105       1 resource.go:271] List called with key: projectcalico.org/ipamconfigurations on resource IPAMConfiguration
E0203 06:08:51.979503       1 status.go:71] apiserver received an error that is not an metav1.Status: errors.ErrorConnectionUnauthorized{Err:(*errors.StatusError)(0xc0012026e0)}: connection is unauthorized: ipamconfigs.crd.projectcalico.org is forbidden: User "system:serviceaccount:calico-apiserver:calico-apiserver" cannot list resource "ipamconfigs" in API group "crd.projectcalico.org" at the cluster scope
time="2023-02-03T06:08:58Z" level=info msg="Process backend watcher done event in main client"
```

**Additional context**
Execute the following command
```
kubectl edit clusterrole calico-crds resource
```
add ipamconfigs can solve
<img width="560" alt="image" src="https://user-images.githubusercontent.com/57695165/216535937-085a6fab-d0ff-434c-920a-08950a46c764.png">

**Comment by hangscer8** [comment]
问题排查中

**Comment by zgfh** [comment]
就关闭了？也没任何解释？
