### ISSUE TITLE
feature: if a kubean operator pod crash, the cluster relevant status will not be updated when the job in progress。

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#508]
as title described:
kubean may need a roll poling mechanism

**Comment by wenting-guo** [comment]
need test step:
1. apply yamls to start a job to create a clusterA  
2. scale the kubean pod replicas to 0
3. after the install job finished, check the clusterA status recored in kubean

**Comment by hangscer8** [comment]
fix by https://github.com/kubean-io/kubean/pull/831
