### ISSUE TITLE
Supports heterogeneous operating systems

### ISSUE THREAD

**Issue by yanrongshi** [kubean-io/kubean#528]
For heterogeneous versions of the platform (including upgrade and Xinchuang), the multi-cluster management platform can be used to realize service migration and reduce user cluster migration costs.

**Comment by ErikJiang** [comment]
See also the parameter `allow_unsupported_distribution_setup`

https://github.com/kubernetes-sigs/kubespray/blob/master/inventory/sample/group_vars/all/all.yml#L139
