### ISSUE TITLE
when interrupting import_iso.sh, the directory should umount, but it doesn't

### ISSUE THREAD

**Issue by XiuguangHuang** [kubean-io/kubean#574]
When we run import_iso.sh, if this operation is interrupted, the directory that has been mounted will not umount. If we try import_iso.sh again, it will say the directory has been mounted.

https://github.com/kubean-io/kubean/blob/main/artifacts/import_iso.sh

**Comment by hangscer8** [comment]
fix by https://github.com/kubean-io/kubean/pull/624
