### ISSUE TITLE
feature: after the cluster deployed ,add retry when send the kubeconf, to avoid failures such as intermittent network disconnection

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#59]
as title

**Comment by ErikJiang** [comment]
It is expected to take time to deal with it in September

**Comment by tukwila** [comment]
i met the same issue. Check cluster is ok:
<img width="859" alt="wecom-temp-e189ea6765c9a80a998f8ce0c5bb3dc2" src="https://user-images.githubusercontent.com/13757056/190038840-8abf532b-6ad9-4196-98e2-23f5fc26ee76.png">
