### ISSUE TITLE
failed to create clusters with docker in kylin os.

### ISSUE THREAD

**Issue by XiuguangHuang** [kubean-io/kubean#602]
failed to create clusters with docker in kylin os.
docker version: 20.10

![企业微信截图_dc62f275-d619-45d8-8bdb-1d7eb56b14d8](https://user-images.githubusercontent.com/96054687/227452560-43a5f96f-1817-49f9-b90b-b52833c0af80.png)

**Comment by ErikJiang** [comment]
https://github.com/kubean-io/kubean/blob/main/build/os-packages/packages.yml#L50

Only docker version 19 is supported on Kylin OS.
