### ISSUE TITLE
When installing kubean in the kube-system namespace, the node check prompts that there is no kubean-system in this namespace

### ISSUE THREAD

**Issue by zizhufanqing** [kubean-io/kubean#638]
The version of kubean is v0.4.8 installed in the namespace of kube system, and the installation was successful without any errors

When creating a cluster through kubean, it prompts that the kubean system space does not exist

Later, I manually created the kubean system and found that I was connecting to the address shown in the figure
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/53900290/231712193-f2a25a82-c359-445b-959e-f133eaa29166.png">
Error reporting 404

**Comment by wenting-guo** [comment]
please report this to kpanda
