### ISSUE TITLE
idea: keep kubespray color

### ISSUE THREAD

**Issue by yankay** [kubean-io/kubean#64]
The KubeSpray output is colorful.

![企业微信截图_16608823239814](https://user-images.githubusercontent.com/1469319/185541268-683b866b-3932-4cd7-92a2-ebe970843a9d.png)
.
But the kubectl logs lost the color. So there is the idea.

The color is a little useful but may have side effects. So I think it's "nice to have" and not "required".

**Comment by hangscer8** [comment]
I will look into it.

**Comment by ErikJiang** [comment]
This method can highlight the log, but it cannot restore the original effect of the ansible log:
* https://github.com/kubernetes/kubectl/issues/524#issuecomment-459028694
* https://github.com/kubernetes/kubectl/issues/524#issuecomment-566448892

@hangscer8

**Comment by wenting-guo** [comment]
not to do
