### ISSUE TITLE
CI failure: when create online calico cluster, failed because of the calico related image pull rate is too slow

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#658]
the default timeout time is 300s, but the pull image procedure spend about 300s, so the creation of cluster fails
![企业微信截图_0a39f4cb-27ce-40f2-8c0e-ac0f95355b75](https://user-images.githubusercontent.com/99961476/232456395-ad3502c5-2ba7-4111-bfe5-8700a90f3dab.png)
![企业微信截图_ffe35b7b-127b-4b8e-adef-ffba3abe8b71](https://user-images.githubusercontent.com/99961476/232456420-ad6f8954-dd0c-441b-a8a6-c1f72ad9f1f7.png)
![企业微信截图_9b94e022-e420-4f4a-8fe4-b22ba3d6194e](https://user-images.githubusercontent.com/99961476/232457021-28142f85-eed1-4c39-b96b-938a1d6cdc5e.png)

**Comment by yankay** [comment]
we can use to https://gist.github.com/yankay/52ec6efe6d49631e5f673a22eb5b1ca5 , to speed up :-)
