### ISSUE TITLE
software bug: online create calico cluster fail

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#665]
**Describe the version**
version about:
1. kubean: v0.4.9
2. kubespray
3. kubenetes
4. what CNI and itsversion

**Describe the bug**
create a calico cluster, will fail
![企业微信截图_a31f6a27-0316-4982-99a4-454d9fec4936](https://user-images.githubusercontent.com/99961476/232976468-c16687d9-71d9-4a51-bc69-0f145381b58a.png)

**Comment by ErikJiang** [comment]
![image](https://user-images.githubusercontent.com/10629406/232979017-2351b908-8349-4387-a193-416238f4d46e.png)

**Comment by yankay** [comment]
Calico 修改过他的二进制文件。导致国内镜像错误，修好了。

**Comment by wenting-guo** [comment]
resolved
