### ISSUE TITLE
An error occurred while creating a cluster for the Redhat8 operating system

### ISSUE THREAD

**Issue by shijinye** [kubean-io/kubean#703]
**Describe the version**
version about:
1. kubean
2. kubespray
3. kubenetes
4. what CNI and itsversion

**Describe the bug**
An error occurred while creating a cluster for the Redhat8 operating system

**How To Reproduce**
Steps to reproduce the issue:
1、kpanda list - create redhat8 cluster（docker20.10） - input vm ipaddr，configure customize value （ 1、 rhel_enable_repos：false  2、docker_rh_repo_gpgkey: ‘’） - final ，create failed

**Expected behavior**

**Screenshots and log**
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/36811869/236848147-d305ef46-4600-4fdd-86d7-1a10b003b013.png">

**Additional context**

**Comment by wenting-guo** [comment]
not kubean problem
