### ISSUE TITLE
Add os kernel version on playbooks/precheck.yml

### ISSUE THREAD

**Issue by yanrongshi** [kubean-io/kubean#705]
When creating a cluster, if choosing to use cilium as the network plugin, cilium requires a system kernel version of >= 4.9.17. Therefore, it is necessary to check the kernel version of the nodes in advance during node inspection, so that users can be given more friendly tips when choosing cilium mode.

```yaml
https://github.com/kubean-io/kubean/blob/7638a75694b8ab95f9711a1ef44987c52a83b7d5/playbooks/precheck.yml#L77
```

**Comment by ErikJiang** [comment]
https://github.com/kubernetes-sigs/kubespray/blob/master/roles/network_plugin/cilium/tasks/check.yml#L23-L30
