### ISSUE TITLE
Kubean image missing vulnerabilities check

### ISSUE THREAD

**Issue by Rei1010** [kubean-io/kubean#708]
**Describe the version**
version about:
1. kubean

**Describe the bug**
Kubean image missing vulnerabilities check

**How To Reproduce**
Using trivy scan related images

**Expected behavior**
No HIGH & CRITICAL vulnerabilities

**Screenshots and log**
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/56469400/237059936-38969333-7e9d-4dae-be91-eff64e7d4c46.png">

**Additional context**
Ref: https://github.com/kubean-io/kubean/actions/runs/4921965903/jobs/8792697667

**Comment by hangscer8** [comment]
fix by 
* https://github.com/kubean-io/kubean/pull/719
* https://github.com/kubean-io/kubean/pull/721
