### ISSUE TITLE
[docs] can be translated to "Change the language selection entry for the documentation site

### ISSUE THREAD

**Issue by yanrongshi** [kubean-io/kubean#750]
## request
The document plugin currently has a built-in language selection plugin for Chinese and English, but we are not using it. Instead, we have added a language toggle table to the left navigation, which seems to be unreasonable.

![image](https://github.com/kubean-io/kubean/assets/29862632/a796b2f0-2a2a-467f-8d27-72b0e1e3039b)

**Comment by ErikJiang** [comment]
fixed
