### ISSUE TITLE
software bug: kubean supported k8s version list is not match to the kubespray k8s version in helm manifest.cr.yaml

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#757]
**Describe the version**
version about:
1. kubean: v0.5.3
2. kubespray
3. kubenetes
4. what CNI and itsversion

**Describe the bug**

the lowest k8s version  supported by kubean is 1.24.0 
https://github.com/kubean-io/kubean-helm-chart/blob/main/charts/kubean/templates/manifest.cr.yaml#LL118C14-L118C14

the  lowest k8s version  supported by kubespray is 1.25.0
https://github.com/kubernetes-sigs/kubespray/blob/master/roles/download/defaults/main.yml#L233

**Comment by hangscer8** [comment]
kubesprayVersion: "f264426"

<img width="1440" alt="企业微信截图_ebfb99bd-a59a-479a-affb-fd5fab76410b" src="https://github.com/kubean-io/kubean/assets/28976713/8b210c48-3243-4550-8a75-d44e13502093">
