### ISSUE TITLE
Creating an arm work cluster reports create token failure

### ISSUE THREAD

**Issue by yulng** [kubean-io/kubean#770]
Creating an arm work cluster reports create token failure

<img width="1353" alt="企业微信截图_e3a6bf21-95b2-4d2e-915e-e40e0a56fe75" src="https://github.com/kubean-io/kubean/assets/31728060/f062f7aa-30b1-48f6-b787-b5ffa38ddd37">

Version: kubean: 0.4.9-rc1
global master:10.16.10.121
ignition machine:10.16.10.120
arm vm :10.5.127.222
step
1. Upload arm related files, images, os pkgs, iso to the ignition machine (10.16.10.120) as attach 
[importimages-arm.txt](https://github.com/kubean-io/kubean/files/11581996/importimages-arm.txt)

2. Successfully imported mini and registry

3. UI using arm virtual machine 10.5.127.222 to Creat work cluster
Timed out waiting for the condition nTo see the stack trace of this error execute with -- v=5 or higher
Analysis:
Execute/usr/local/bin/kubeadm on the VM -- kubeconfig/etc/kubernetes/admin. conf token create

<img width="1414" alt="企业微信截图_14947347-13de-42b5-8894-ccbf94ad77bf" src="https://github.com/kubean-io/kubean/assets/31728060/ff4c3bcd-47ad-4086-bde9-c4f450f57e88">

Simultaneously view nerdctl ps, as shown in the figure

<img width="1377" alt="企业微信截图_de7c0084-0888-455f-9501-b5e711bb0541" src="https://github.com/kubean-io/kubean/assets/31728060/5815e420-1597-49f7-9e39-d4f3cfa0f9ac">

<img width="1343" alt="企业微信截图_63bf69bc-ac1b-4299-b807-fab3728c77d6" src="https://github.com/kubean-io/kubean/assets/31728060/55fb5e37-8fe7-4add-b0ce-9a07024d8ad9">

<img width="1376" alt="企业微信截图_61e06501-e30d-422e-8624-c1e0c9d8c471" src="https://github.com/kubean-io/kubean/assets/31728060/309444f8-1a79-41cc-b7bb-5b385b0b1a85">

[arm创建失败.txt](https://github.com/kubean-io/kubean/files/11582016/arm.txt)

**Comment by tu1h** [comment]
It was failed since kube-apiserver and others didn't startup. 

From the logs, this is the second time the deployment process has been performed after the first failure. And there is no first process log provided, so we can't find some clues about the breakdown of kube-apiserver.
