### ISSUE TITLE
software bug: Incomplete sudo permission check

### ISSUE THREAD

**Issue by tu1h** [kubean-io/kubean#804]
**Describe the version**
version about:
1. kubean v0.6.1
2. kubespray
3. kubenetes
4. what CNI and itsversion

**Describe the bug**
Context from https://github.com/kubean-io/kubean/pull/793/files#diff-9864c355f2595089183328d45da2d99c2b0d6802d78b1d58f8879b1c47aa227dR33.
But there is no sudo group in some OS(like CentOS 7.9).

![image](https://github.com/kubean-io/kubean/assets/92532497/d74a4723-8010-4bdd-9922-88f5d50e3108)

**Comment by hangscer8** [comment]
ACK

**Comment by hangscer8** [comment]
fix by https://github.com/kubean-io/kubean/pull/809
