### ISSUE TITLE
create 1+1 cluster,error: exec: \\\"cp\\\": executable file not found in $PATH: unknown\"",

### ISSUE THREAD

**Issue by yulng** [kubean-io/kubean#815]
[demo-dev]10.6.229.192
[kubean version]ghcr.m.daocloud.io/kubean-io/spray-job:v0.6.1-7-ge0d10a35-main
![企业微信截图_e35ae7fb-a34e-4589-9731-1ad85541f52f](https://github.com/kubean-io/kubean/assets/31728060/e090afd7-2657-49ba-846e-9f4038e7adb2)

yml:
![image](https://github.com/kubean-io/kubean/assets/31728060/343fa1bc-4b6d-4709-94ac-0d5d10cea82a)

![image](https://github.com/kubean-io/kubean/assets/31728060/5311c57d-4c88-45f7-adac-c9ea9791ac21)

![Uploading image.png…]()

**Comment by wenting-guo** [comment]
both the kubean v0.5.4 and the v0.6.2 version have the problem

**Comment by hangscer8** [comment]
This issue is fixed in ` v0.6.6`.
