### ISSUE TITLE
feature：kubean need  provide config for audit log save to disk

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#82]
The audit log will be stored on storage pool, so kubean need provide config for the storage address.

**Comment by ErikJiang** [comment]
https://github.com/kubernetes-sigs/kubespray/blob/master/docs/vars.md

![image](https://user-images.githubusercontent.com/10629406/187120026-d0394d59-68e2-4d08-8581-524b17e2f720.png)

**Comment by YunShiHang** [comment]
test

/woof
