### ISSUE TITLE
software bug:close the node network, while create a cluster, after more then 20 minutes, the job pod is still running.

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#823]
**Describe the version**
version about:
1. kubean v0.5.2

**Describe the bug**
create a cluster close the node network, after more then 20 minutes, the job pod is still running.

**How To Reproduce**
1. start a ops to create a one node cluster
2. close the node network: service network stop
3. check the node is not reachalbe
4. wait the ops related pod to be error
5. but i waited more than 20m, the pod is still running

**Expected behavior**
when the cluster node is not reachable for more than such as 20m, the ops related pod should can be stopped

**Screenshots and log**
when close the network, the log of the job:
![image](https://github.com/kubean-io/kubean/assets/99961476/0130ea49-d993-4e75-aee9-fe417801344d)

after close the network ping the node:
![image](https://github.com/kubean-io/kubean/assets/99961476/1b655f55-2bc3-4f7b-8e21-930f85eb1621)

the ops related pod is still running:
![image](https://github.com/kubean-io/kubean/assets/99961476/0b129173-6c28-41e3-b97e-b3b06184962d)

and the logs of the job is still stopped at :
![image](https://github.com/kubean-io/kubean/assets/99961476/85098c1d-ab8d-4ace-99ba-aa17b02b3348)

**Comment by ErikJiang** [comment]
The [`spec.activeDeadlineSeconds`](https://github.com/kubean-io/kubean/blob/main/charts/kubean/crds/kubean.io_clusteroperations.yaml#L60C15-L60C36) parameter can be set in the `clusterOperation`
