### ISSUE TITLE
documentation issue: the png file is not exsit, so the picturen can not showed in ./docs/zh/concepts/architecture.md

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#824]
**Documentation issue**

the target file: https://github.com/kubean-io/kubean/blob/main/docs/zh/concepts/architecture.md

![image](https://github.com/kubean-io/kubean/assets/99961476/b04fed7a-391c-493e-aa6a-f35839ab2767)

![image](https://github.com/kubean-io/kubean/assets/99961476/cf4ab587-7c97-4ede-b452-a56b9ed4ce84)

**Comment by yulng** [comment]
The document is correct
https://kubean-io.github.io/kubean/en/concepts/architecture/
