### ISSUE TITLE
create 3master+vip cluster ,the vip can not be pinged by kubean

### ISSUE THREAD

**Issue by yulng** [kubean-io/kubean#828]
**Describe the version**
version about:
1. kubean :0.6.1
2. kubenetes:workload 1.25.3

**Describe the bug**
create 3master+vip cluster ,the vip can not be pinged

**How To Reproduce**
1 create 3master+vip cluster
2 vip can be ping by manually
3 but vip can not be pinged by kubean
![企业微信截图_d671ac32-0d9e-4c69-9568-51d3f908d8fa](https://github.com/kubean-io/kubean/assets/31728060/2020fed4-6caf-42d8-acc7-e684aaa710f2)

**Expected behavior**
vip can be pinged by kubean(auto)

**Comment by hangscer8** [comment]
fix by https://github.com/kubean-io/kubean/pull/830
