### ISSUE TITLE
Update the cluster certificate and upgrade the cluster version

### ISSUE THREAD

**Issue by yanrongshi** [kubean-io/kubean#84]
**usage issue**
1. Will services be interrupted when the cluster upgrades the KUBE version? Can users create or upgrade resources (loads)? 2. Will services be interrupted when ** Adding ** or ** deleting ** of a node in a cluster created based on KuBean? Can users create or upgrade resources (loads)? 
3. Check whether services are interrupted when the certificate is updated. Can users create or upgrade resources (loads)? 
4. Is the certificate updated automatically on the first weekend of each month? If a certificate is obtained before the certificate is updated, can the certificate still be used after the certificate is updated?
5. Can I use the interface to update the certificate?

**Comment by ErikJiang** [comment]
1. 升级 K8S 版本业务不会中断(除单节点集群外), 工作负载的创建与升级需要最好是在集群升级完成以后, 否则可能会发生Pod漂移;
2. 增删工作节点不会中断业务, 但业务Pod可能会因此漂移到其他节点;
3. 证书更新业务是否中断, 可以请 @wenting-guo @tukwila 帮忙验证一下
4. 证书更新需要通过变量开关设置, 开启后默认每个月第一周更新, 更新后旧证书无法使用, 目前没有接口更新证书, 需要部署时启动变量开关

@yanrongshi

**Comment by ErikJiang** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal

> After running the command you should restart the control plane Pods. This is required since dynamic certificate reload is currently not supported for all components and certificates.

@yanrongshi
