### ISSUE TITLE
job failed to start a new pod after I delete the pod which is in "error" state

### ISSUE THREAD

**Issue by todaygood** [kubean-io/kubean#843]
**Describe the version**
version about:
1. kubean  0.6.3
2. kubespray
3. kubenetes :latest
4. what CNI and itsversion : calico

**Describe the bug**
job failed to start a new pod after I delete the pod which is in "error" state

**How To Reproduce**
Steps to reproduce the issue:

**Expected behavior**
start a new pod to deploy k8s cluster.

**Screenshots and log**
```bash

[root@pcentos ~]# kubectl  get po -A 
NAMESPACE       NAME                                        READY   STATUS      RESTARTS   AGE
kubean-system   kubean-59687dfd7d-q8krf                     1/1     Running     0          33m
kubean-system   kubean-cluster-mini-install-ops-job-b9fjz   0/1     Error       0          28m

TASK [container-engine/runc : download_file | Get the list of working mirrors] ***
ok: [node1]
Sunday 18 June 2023  14:34:57 +0000 (0:00:00.889)       0:17:05.376 *********** 
FAILED - RETRYING: [node1]: download_file | Download item (4 retries left).
FAILED - RETRYING: [node1]: download_file | Download item (3 retries left).
FAILED - RETRYING: [node1]: download_file | Download item (2 retries left).
FAILED - RETRYING: [node1]: download_file | Download item (1 retries left).

TASK [container-engine/runc : download_file | Download item] *******************
fatal: [node1]: FAILED! => {"attempts": 4, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
```

**Comment by tu1h** [comment]
Can your network get Internet? Or the binaries(e.g. runc) almost locate out of China, so maybe you could use [mirror](https://github.com/kubean-io/kubean/blob/main/examples/install/2.mirror/VarsConfCM.yml#L31-L53) instead. :-)

**Comment by tu1h** [comment]
You could increase [backoffLimit](https://github.com/kubean-io/kubean/blob/main/examples/install/1.minimal/AllInOne.yml#L70) to retry. And maybe you could use [mirror](https://github.com/kubean-io/kubean/blob/main/examples/install/2.mirror/VarsConfCM.yml#L31-L53) instead, because the binaries(e.g. runc) almost locate at out of China.
