### ISSUE TITLE
documentation issue about use of airgap scenarios 

### ISSUE THREAD

**Issue by yulng** [kubean-io/kubean#854]
**Documentation issue**
https://kubean-io.github.io/kubean/zh/usage/airgap/

1 MINIO_ USER=${username} MINIO_ PASS=${password}/ Import_ Files. sh ${mino_address}
The directive is missing the file name for offline files. tar.gz
2 $DEST_ USER=${username} DEST_ PASS=${password}/ Import_ Images. sh ${registry_address}
The directive is missing the file name for offline images. tar. gz
3 ISO image source: The $releasever $basearch two variables in do not need to be filled in, Linux internal variables
4 Currently, only the Centos distribution is supported and changed to the Redhat series
5 "ClusterOperation combined with playbook to create source configuration files" will automatically create setup repo files on each node, eliminating the need for manual 1.2 to establish online ISO image sources

1. $ MINIO_USER=${username} MINIO_PASS=${password} ./import_files.sh ${minio_address}
指令缺少  offline-files.tar.gz 的文件名称
2 $ DEST_USER=${username} DEST_PASS=${password} ./import_images.sh ${registry_address}
指令缺少  offline-images.tar.gz 的文件名称
3  ISO 镜像源:中的$releasever  $basearch 两个变量不需要填写 ,linux内部变量
4 当前仅支持 Centos 发行版 改为redhat系列
5 "ClusterOperation 结合 playbook 创建源配置文件"就会去各个节点上自动的创建设置repo文件，就不需要手动1.2建立在线 ISO 镜像源

**Comment by tu1h** [comment]
- Within the current design, it's undesired to pass file path to [import_files.sh](https://github.com/kubean-io/kubean/blob/main/artifacts/import_files.sh) and [import_images.sh](https://github.com/kubean-io/kubean/blob/main/artifacts/import_images.sh).

- About your point 3, we need not replace variables `$releasever` and `$basearch`. All variables that need to be replaced are declared definitely.

- The last one, we will improve it.

Thanks for your catching!
