### ISSUE TITLE
e2e CI failure :name 'PEP440Version' is not defined"

### ISSUE THREAD

**Issue by yulng** [kubean-io/kubean#857]
**Describe the version**
version about:
1. kubean:v0.6.6-13-ge3831fb2-e2e
**Describe the bug**
e2e create 3master vip test case
In the use case of e2e, when creating a cluster and building a kubesray version

**Screenshots and log**
https://github.com/kubean-io/kubean/actions/runs/5417793162/jobs/9849150856

<img width="954" alt="企业微信截图_d5f6d76f-f09b-45f5-9ef9-fc8ddd063ca1" src="https://github.com/kubean-io/kubean/assets/31728060/144b9177-9977-4713-904c-22c75a90395e">

<img width="991" alt="企业微信截图_08382ef3-0449-4546-a4ed-e26e885df22a" src="https://github.com/kubean-io/kubean/assets/31728060/882badd2-141b-4fe5-bb23-729244e4be68">

**Comment by tu1h** [comment]
spray-job image is missing python package `packaging`
