### ISSUE TITLE
[CI failure] Auto Offline failed :ansible_pkg_mgr' is undefined

### ISSUE THREAD

**Issue by yulng** [kubean-io/kubean#868]
**Describe the version**
version about:
1. kubean v0.7.0 
2. kubenetes node:v1.26.4

**Describe the bug**
<img width="1388" alt="企业微信截图_98a2b283-1f63-4d5f-a891-6f773c05425c" src="https://github.com/kubean-io/kubean/assets/31728060/6d0726bd-9a68-42d0-b510-c261ff03975c">
fatal: [node1]: FAILED! => {"msg": "The conditional check 'ansible_pkg_mgr == 'apt'' failed. The error was: error while evaluating conditional (ansible_pkg_mgr == 'apt'): 'ansible_pkg_mgr' is undefined. 'ansible_pkg_mgr' is undefined\n\nThe error appears to be in '/kubespray/enable-repo.yml': line 65, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.
https://github.com/kubean-io/kubean/actions/runs/5468482042/jobs/9957168677

**How To Reproduce**
Steps to reproduce the issue:
offline to run this case kubean_cluster_os_compatibility_test.go

**Comment by ErikJiang** [comment]
The error only occurs when ansible version is 2.14
```
kubean-sleep-infinity-sample-job-s9tft:/kubespray# ansible --version
ansible [core 2.14.6]
  config file = /kubespray/ansible.cfg
  configured module search path = ['/kubespray/library']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun  9 2023, 02:29:43) [GCC 12.2.1 20220924] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = False
```

ansible_pkg_mgr is undefined when ansible_distribution is "Kylin Linux Advanced Server"

**Comment by ErikJiang** [comment]
![image](https://github.com/kubean-io/kubean/assets/10629406/0ce060a1-03bb-4875-8623-7caebc485e03)
The issue triggered a chain reaction
