### ISSUE TITLE
support-k8s-version.md prompt 404

### ISSUE THREAD

**Issue by tukwila** [kubean-io/kubean#878]
support-k8s-version.md cannot display:
https://github.com/kubean-io/kubean/blob/main/docs/zh/usage/support-k8s-version.md

<img width="935" alt="image" src="https://github.com/kubean-io/kubean/assets/13757056/b10607c6-0fff-4809-a516-155acd1bf16e">

**Comment by Rei1010** [comment]
current path is https://github.com/kubean-io/kubean/blob/main/docs/zh/usage/support_k8s_version.md
