### ISSUE TITLE
[Actions] optimize images building workflow to save more time

### ISSUE THREAD

**Issue by tukwila** [kubean-io/kubean#883]
**1 Code requirement**

necessary comment for your additional code , and comment for goDoc

function and variable name must not be at will

do not make huge function

https://github.com/kubean-io/kubean/actions/runs/5552131265

In the following screenshot, spray-job image and airgap patches is dependent on kubespray basic image except kubean-operator image, it is better to reorganize this workflow to speed up image building process.

<img width="294" alt="image" src="https://github.com/kubean-io/kubean/assets/13757056/e8a86de6-693e-452f-97d6-b287c8cbb21b">

**2 observe opensource license**

announce license at the beginning of file

**3 sign-off your commit**

your commit must be signed off

**4 Is your feature request related to a problem? Please describe.**

**5 Describe the solution you'd like**

Building images are imported both by release kubespray-verify workflow. But in kubespray-verify workflow senario, airgap patches is not required. So, it should be skipped.

**6 Describe alternatives you've considered**

**7 Additional context**

**Comment by tu1h** [comment]
A nice propose, we plan to process in next milestone
