### ISSUE TITLE
[cluster verify]Will cluster deploying process continue when kubean deploy process break

### ISSUE THREAD

**Issue by tukwila** [kubean-io/kubean#888]
**Describe the version**
version about:
1. kubean
2. kubespray
3. kubenetes
4. what CNI and itsversion

**Describe the bug**
This scenario should be verified manually:
1. Assume that kubean is deploying one cluster and spray job status is running, cluster servers break such as power off or shutdown or  network cutdown in this process; how about spray job in such scenario? Is it continue for some time or break at once?

2. Continue with item 1, assume that servers are back in short time, how about spray job? If spray job can continue to deploy cluster, it is recommended that kubean can detect such breakoff and don't need to rerun the last job.

**How To Reproduce**
Steps to reproduce the issue:

**Expected behavior**

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

**Additional context**

**Comment by tu1h** [comment]
Currently, when the node on which a running spray-job is running suddenly goes down or has a power outage and the node starts up again, the job will start another pod to execute the task, and it will again execute the process that the previous pod has already executed.
