### ISSUE TITLE
software bug after i installed kubean by helm , and use the sugested cmd to check kubean status. I got "Error: release: not found.

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#89]
**Describe the version**
version about:
1. kubean: v0.0.1

**Describe the bug**
as title

**How To Reproduce**
install kubean: helm install kubean kubean-io/kubean --create-namespace -n kubean-system
and then use cmd showed in install info: 
’‘’
To learn more about the release, try:

  $ helm status kubean
  $ helm get all kubean
‘’‘
I got:  'Error: release: not found'

**Expected behavior**
i can get kubean status use the suggested cmd

**Comment by hangscer8** [comment]
the output `$ helm status kubean  $ helm get all kubean` shown after the operation of helm install  is not very precise.

The output should be `helm status kubean -n kubean-system`.
