### ISSUE TITLE
check kubecost efficiency, should meet the criteria

### ISSUE THREAD

**Issue by liyuerich** [kubean-io/kubean#896]
**1 efficiency requirement**

please check kubecost efficiency, should meet this criteria:

KubeCost Efficiency >=40% , and memory Efficiency <=130%

![image](https://github.com/kubean-io/kubean/assets/97269208/fcb4ff83-fd38-465c-b142-b5e751c2eaf6)

**Comment by tu1h** [comment]
We'll make the checking in the next milestone

**Comment by liyuerich** [comment]
check at Oct 26

![image](https://github.com/kubean-io/kubean/assets/97269208/9754e9dd-78a1-4506-a4b2-6087978889cd)

**Comment by liyuerich** [comment]
check at Dec 25

![image](https://github.com/kubean-io/kubean/assets/97269208/1559c774-530f-42ec-a44b-ac32b71f84fd)
