### ISSUE TITLE
join kylin work node in redhat8 cluster，but pull amd image，then failed

### ISSUE THREAD

**Issue by shijinye** [kubean-io/kubean#898]
**Describe the version**
version about:
1. kubean
2. kubespray
3. kubenetes
4. what CNI and itsversion

**Describe the bug**
join kylin work node，but pull amd image，then failed

**How To Reproduce**
Steps to reproduce the issue:

**Expected behavior**

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

**Additional context**

**Comment by tu1h** [comment]
Please provide some details(logs, OS info, etc). -:)

But I think you met a situation like https://github.com/kubernetes-sigs/kubespray/issues/9126
