### ISSUE TITLE
CNCF TAG-Runtime Discussion/Presentation

### ISSUE THREAD

**Issue by rajaskakodkar** [kubean-io/kubean#899]
Hello Kubean maintainers,

As part of [CNCF TAG Runtime](https://github.com/cncf/tag-runtime), I am reaching out to you to present/discuss Kubean at one of our meetings, since you have also applied for Sandbox (cncf/sandbox#49). 

It would be great to learn about the roadmap of the project, tech, community and the general overview. 

If you are interested, there is a slot on 31st Aug on our [agenda](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit#heading=h.h8tr1lub79a3). Please feel free to add it to the agenda or reach out to us in the [#tag-runtime](https://slack.cncf.io/) channel on the CNCF slack.

Thanks!

cc: @raravena80 @helayoty @nikhita

**Comment by rajaskakodkar** [comment]
@ErikJiang awesome! I have updated the [agenda](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit?pli=1#heading=h.166fz2gnqvyk).

**Comment by rajaskakodkar** [comment]
@ErikJiang gentle reminder that this is scheduled for tomorrow! https://cloud-native.slack.com/archives/CPBE97SMU/p1693395403253659

**Comment by panpan0000** [comment]
Links below:

The Slides for the intro in tag meeting:
https://docs.google.com/presentation/d/1Gh-Y8t4QGrq4s2nYI5YR0rycVHjQcmEOtxB1Xqotqr8/edit?usp=sharing

Recording for the meeting:
https://www.youtube.com/watch?v=CrPr7TqEIrc&list=PL6wYrb-bYwC_iStEfVmBpLKDBqOy23nCA&index=44

More discussion for sandbox:
https://github.com/cncf/sandbox/issues/49
