### ISSUE TITLE
在redhat 9.2中如何使用

### ISSUE THREAD

**Issue by Queetinliu** [kubean-io/kubean#913]
我的操作系统是redhat 9.2 ，我没有注册redhat，请问我如何使用kubean？需要做什么设置呢？

**Comment by ErikJiang** [comment]
Need to do offline adaptation, pending.

**Comment by tu1h** [comment]
In airgap(offline) scenario, it will be supported after https://github.com/kubean-io/kubean/pull/930 .

In Internet scenario, it is supported natively. Just set options in Kubean's vars conf:
```yaml
rh_subscription_username: ""
rh_subscription_password: ""
rh_subscription_usage: "Development"
rh_subscription_role: "Red Hat Enterprise Server"
rh_subscription_sla: "Self-Support"
```
