### ISSUE TITLE
software bug：use kubean to install a cluster, the log showed that the install procedure was failed, but actually the cluster was installed successfully

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#93]
**Describe the version**
version about:
1. kubean :  commit  e4d6fc3da8787b928d1a3781499c
2. kubespray
3. kubenetes 1.24
4. what CNI and itsversion

**Describe the bug**
1.  install a one master and one worker cluster
at the end of the ops log, i saw : 

TASK [Show cluster info] *******************************************************
fatal: [master1]: FAILED! => {"changed": true, "cmd": "kubectl get node -o wide\nkubectl -n kube-system get pod\nkubectl get --raw='/readyz?verbose'\n", "delta": "0:00:00.010707", "end": "2022-08-26 10:34:10.399262", "msg": "non-zero return code", "rc": 127, "start": "2022-08-26 10:34:10.388555", "stderr": "/bin/sh: kubectl: command not found\n/bin/sh: line 1: kubectl: command not found\n/bin/sh: line 2: kubectl: command not found", "stderr_lines": ["/bin/sh: kubectl: command not found", "/bin/sh: line 1: kubectl: command not found", "/bin/sh: line 2: kubectl: command not found"], "stdout": "", "stdout_lines": []}

2. I login the cluster i confirm the cluster was successfully installed.

kubectl get node
NAME      STATUS   ROLES           AGE     VERSION
master1   Ready    control-plane   4h11m   v1.24.4
node1     Ready    <none>          4h9m    v1.24.4

kubectl get pod -A
NAMESPACE     NAME                              READY   STATUS    RESTARTS        AGE
kube-system   calico-node-dt2nk                 1/1     Running   0               4h9m
kube-system   calico-node-fr2wb                 1/1     Running   0               4h9m
kube-system   coredns-58795d59cc-64sr8          1/1     Running   0               4h6m
kube-system   coredns-58795d59cc-7mn5z          1/1     Running   0               4h6m
kube-system   dns-autoscaler-bf5f67d8d-bw9dh    1/1     Running   0               4h6m
kube-system   kube-apiserver-master1            1/1     Running   1               4h12m
kube-system   kube-controller-manager-master1   1/1     Running   5 (3h36m ago)   4h12m
kube-system   kube-proxy-cnxn2                  1/1     Running   0               4h10m
kube-system   kube-proxy-n8ng2                  1/1     Running   0               4h10m
kube-system   kube-scheduler-master1            1/1     Running   6 (157m ago)    4h12m
kube-system   nginx-proxy-node1                 1/1     Running   0               4h10m

**Screenshots and log**
IPLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
master1                    : ok=629  changed=168  unreachable=0    failed=0    skipped=1043 rescued=0    ignored=8   
node1                      : ok=332  changed=101  unreachable=0    failed=0    skipped=576  rescued=0    ignored=0   

Friday 26 August 2022  02:33:42 +0000 (0:00:00.136)       0:33:37.588 ********* 
=============================================================================== 
kubernetes/control-plane : kubeadm | Initialize first master ---------- 176.83s
bootstrap-os : Install libselinux python package ---------------------- 157.22s
download : download_file | Download item ------------------------------ 143.92s
network_plugin/calico : Wait for calico kubeconfig to be created ------ 102.83s
download : download_file | Download item ------------------------------- 90.37s
kubernetes/preinstall : Install packages requirements ------------------ 89.24s
download : download_file | Download item ------------------------------- 74.19s
download : download_file | Download item ------------------------------- 67.05s
container-engine/crictl : download_file | Download item ---------------- 63.74s
container-engine/runc : download_file | Download item ------------------ 45.29s
download : download_file | Download item ------------------------------- 39.22s
kubernetes/kubeadm : Join to cluster ----------------------------------- 38.96s
download : download_file | Validate mirrors ---------------------------- 29.42s
download : download_file | Download item ------------------------------- 28.97s
download : download_file | Download item ------------------------------- 28.56s
network_plugin/calico : Calico | Create Calico Kubernetes datastore resources -- 25.98s
kubernetes/preinstall : Force Sync NTP Immediately --------------------- 17.30s
kubernetes/kubeadm : Kubeadm | reload kubelet -------------------------- 16.71s
container-engine/containerd : download_file | Download item ------------ 15.08s
container-engine/nerdctl : download_file | Download item --------------- 13.27s
+ inventory_file=/conf/hosts.yml
++ yq e .all.children.kube_control_plane.hosts /conf/hosts.yml -o y
++ head -n 1
++ cut -f1 -d:
+ first_master=master1
++ yq e .all.hosts.master1.ip /conf/hosts.yml -o y
+ first_master_ip=10.6.178.21
+ kubeconfig_name=cluster-21-22-key-kubeconf
+ fetch_src=/root/.kube/config
+ fetch_dest=/root/cluster-21-22-key-kubeconf
+ ansible -i /conf/hosts.yml master1 -m fetch -a 'src=/root/.kube/config dest=/root/cluster-21-22-key-kubeconf' --private-key /auth/ssh-privatekey
[WARNING]: Skipping callback plugin 'ara_default', unable to load
master1 | CHANGED => {
    "changed": true,
    "checksum": "5ccafb650c57358876ae8bf7b834185dcc229912",
    "dest": "/root/cluster-21-22-key-kubeconf/master1/root/.kube/config",
    "md5sum": "7d25ad36079d795596477b53ad5856b2",
    "remote_checksum": "5ccafb650c57358876ae8bf7b834185dcc229912",
    "remote_md5sum": null
}
+ sed -i 's/127.0.0.1:.*/10.6.178.21:6443/' /root/cluster-21-22-key-kubeconf/master1/root/.kube/config
+ set +e
++ grep cluster-21-22-key-kubeconf
++ wc -l
++ sed 's/ //g'
++ kubectl -n kubean-system get configmap
+ kubeconf_count=0
+ '[' 0 -gt 0 ']'
+ set -e
+ kubectl -n kubean-system create configmap cluster-21-22-key-kubeconf --from-file=/root/cluster-21-22-key-kubeconf/master1/root/.kube/config
configmap/cluster-21-22-key-kubeconf created
+ kubectl patch --type=merge kubeancluster cluster-21-22-key -p '{"spec": {"kubeconfRef": {"name": "cluster-21-22-key-kubeconf", "namespace": "kubean-system"}}}'
kubeancluster.kubeancluster.kubean.io/cluster-21-22-key patched
+ ansible-playbook -i /conf/hosts.yml -b --become-user root -e @/conf/group_vars.yml --private-key /auth/ssh-privatekey /kubespray/cluster-info.yml
[WARNING]: Skipping callback plugin 'ara_default', unable to load

PLAY [kube_control_plane[0]] ***************************************************
Friday 26 August 2022  02:34:06 +0000 (0:00:00.052)       0:00:00.052 ********* 

TASK [Show cluster info] *******************************************************
fatal: [master1]: FAILED! => {"changed": true, "cmd": "kubectl get node -o wide\nkubectl -n kube-system get pod\nkubectl get --raw='/readyz?verbose'\n", "delta": "0:00:00.010707", "end": "2022-08-26 10:34:10.399262", "msg": "non-zero return code", "rc": 127, "start": "2022-08-26 10:34:10.388555", "stderr": "/bin/sh: kubectl: command not found\n/bin/sh: line 1: kubectl: command not found\n/bin/sh: line 2: kubectl: command not found", "stderr_lines": ["/bin/sh: kubectl: command not found", "/bin/sh: line 1: kubectl: command not found", "/bin/sh: line 2: kubectl: command not found"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT *************

**Additional context**

**Comment by wenting-guo** [comment]
want  add a retry mechanism

**Comment by ErikJiang** [comment]
Added to todo list
