### ISSUE TITLE
CI failure: fail to Download action repository 'actions/checkout@v3

### ISSUE THREAD

**Issue by KubeKyrie** [kubean-io/kubean#945]
Set title to be in the format CI: <test-name>.
CI failure: fail to download action repository 'actions/checkout@v3

Copy-paste the output the test failure.
![image](https://github.com/kubean-io/kubean/assets/139965836/dc889064-de0d-451e-9e05-eef7fff716a2)

Upload the zip file generated from that test failure.

Copy-paste the link of the CI build where that test failure has happen.
https://github.com/kubean-io/kubean/actions/runs/6019615444/job/16330552280?pr=944

Include any output from logs that you think may be relevant (to ease GitHub searches).
actions/checkout has been upgraded recently

**Comment by Rei1010** [comment]
Thanks for your reporting the issue, after debugging, it seemed like network connection issue during the runner and gitlab. 
Also we had no strong reason to upgrade plugin to v4. Will close the issue firstly.
