### ISSUE TITLE
kubean success job log has  "fatal failed xxx" information, very confused

### ISSUE THREAD

**Issue by liyuerich** [kubean-io/kubean#951]
**Describe the version**
version about:
1. kubean
ghcr.io/kubean-io/kubean-operator:v0.7.4
2. kubenetes 
v1.26.5

**Describe the bug**

1. create kubean cluster  from dce kpanda, status is success
2. check the kubean log and there are "fatal xxx"
this is very confused for a successful job

it seems to use "check xxxxx failed"..... skip , should be better. just my understanding.

TASK [Check kubeconfig configmap] **********************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/kubectl -n kubean-system get configmap xxx-kubeconf", "delta": "0:00:00.423699", "end": "2023-09-07 04:20:52.620538", "msg": "non-zero return code", "rc": 1, "start": "2023-09-07 04:20:52.196839", "stderr": "Error from server (NotFound): configmaps \"xxx-kubeconf\" not found", "stderr_lines": ["Error from server (NotFound): configmaps \"xxx-kubeconf\" not found"], "stdout": "", "stdout_lines": []}
...ignoring

![image](https://github.com/kubean-io/kubean/assets/97269208/8469f24e-b4f1-4b8b-8d5c-cbb5891a9240)

![image](https://github.com/kubean-io/kubean/assets/97269208/e76421e9-e7ac-4edb-8d24-ba9873bf8b94)

**Comment by tu1h** [comment]
The error ignore is the mechanism of Ansible. Sometime an error would not block the main process, and might act as a feature, it will be designed with failure-allowing.
