### ISSUE TITLE
 generate k8s offline upgrade package  failed

### ISSUE THREAD

**Issue by liyuerich** [kubean-io/kubean#965]
**Describe the version**
version about:
1. kubean airgap-patch v0.9.0

**Describe the bug**
try to generate k8s offline upgrade package and failed

run this command at my MacBook Pro, Apple M2 Max

docker run --rm -v $(pwd)/manifest.yml:/manifest.yml -v $(pwd)/data:/data -e ZONE=CN ghcr.m.daocloud.io/kubean-io/airgap-patch:v0.9.0

skip to run nginx
/usr/bin/skopeo
skopeo check successfully
begin to download images
create dir offline-images
download image k8s.m.daocloud.io/kube-scheduler:v1.27.0 to local registry.k8s.io%kube-scheduler:v1.27.0
artifacts/generate_offline_package.sh: line 120: /usr/bin/skopeo: cannot execute: required file not found
skopeo copy image failed, image name: registry.k8s.io/kube-scheduler:v1.27.0.

**Comment by hangscer8** [comment]
Fixing
