### ISSUE TITLE
Follow the guide to generate offline patch, actual kube version is not same as manifest.yaml required

### ISSUE THREAD

**Issue by liyuerich** [kubean-io/kubean#968]
**Describe the version**
version about:
1. kubean airgap-patch 0.9.0

**Describe the bug**
Follow the guide to generate offline patch:
1. setup manifest.yaml
image_arch:
  - "amd64" ## "arm64"
kube_version:
  - "v1.27.0"
  - "v1.26.6"

2. check minio package
  it is v1.26.0, v1.27.1
<img width="1234" alt="image" src="https://github.com/kubean-io/kubean/assets/97269208/3bf216a6-2a24-44c7-ab00-b72e1bf3561c">

3. dowload files failed.

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

<img width="1339" alt="image" src="https://github.com/kubean-io/kubean/assets/97269208/b1dd6971-f081-4eef-a409-ea3169107fb1">

**Comment by hangscer8** [comment]
Fixing

**Comment by hangscer8** [comment]
The version of airgap-atch image should be the same as the kubean version which is running in the k8s cluster.

**Comment by liyuerich** [comment]
it  works. thanks
