### ISSUE TITLE
create cluster on redhat OS failed, due to "audit package problems". 

### ISSUE THREAD

**Issue by liyuerich** [kubean-io/kubean#975]
**Describe the version**
version about:
1. kubean 0.9.0

**Describe the bug**
create cluster on redhat OS failed, due to "audit package problems". 

**Screenshots and log**

TASK [kubernetes/preinstall : Install packages requirements] *******************
fatal: [controller-node-1]: FAILED! => {"attempts": 4, "changed": false, "failures": [], "msg": "Depsolve Error occurred: \n Problem: problem with installed package audit-3.0-0.17.20191104git1c2f876.el8.x86_64\n  - package audit-3.0-0.17.20191104git1c2f876.el8.x86_64 requires audit-libs(x86-64) = 3.0-0.17.20191104git1c2f876.el8, but none of the providers can be installed\n  - cannot install both audit-libs-3.0.7-5.el8.x86_64 and audit-libs-3.0-0.17.20191104git1c2f876.el8.x86_64\n  - package python3-audit-3.0.7-5.el8.x86_64 requires audit-libs(x86-64) = 3.0.7-5.el8, but none of the providers can be installed\n  - package python3-policycoreutils-2.9-24.el8.noarch requires audit-libs-python3 >= 3.0, but none of the providers can be installed\n  - package policycoreutils-python-utils-2.9-24.el8.noarch requires python3-policycoreutils = 2.9-24.el8, but none of the providers can be installed\n  - package container-selinux-2:2.218.0-1.module_el8+454+d7ef4b8d.noarch requires policycoreutils-python-utils, but none of the providers can be installed\n  - cannot install the best candidate for the job\n  - package audit-libs-3.0-0.17.20191104git1c2f876.el8.x86_64 is filtered out by modular filtering\n  - package policycoreutils-python-utils-2.9-14.el8.noarch is filtered out by modular filtering\n  - package python3-audit-3.0-0.17.20191104git1c2f876.el8.x86_64 is filtered out by modular filtering", "rc": 1, "results": []}

![image](https://github.com/kubean-io/kubean/assets/97269208/c455b75c-8283-4672-947e-9d6080ba4acd)

**Comment by tu1h** [comment]
Please loopup value of `rhel_enable_repos` which in vars-conf configmap. If `true` or nonexistent, it means you need to set `rhel_enable_repos: false` to the vars-conf.
