### ISSUE TITLE
create Kylin cluster failed

### ISSUE THREAD

**Issue by liyuerich** [kubean-io/kubean#978]
create Kylin cluster failed

1. follow documentation to upload kylin iso and os package
2. upload offline arm 64 tar
3. create cluster failed due to coredns image issue
4. 
<img width="1364" alt="image" src="https://github.com/kubean-io/kubean/assets/97269208/636eeb76-ec0c-4c3f-b8eb-0b36d7c0d89f">

5. temporary solution ：
add  parameters     coredns_image_tag: "v1.9.3-arm64" 

7. retry to create cluster, failed again
due to port is in use ? this is warning , is it the root cause?

![企业微信截图_5d6f2f16-c59f-4a23-b68e-8e7041dc4d18](https://github.com/kubean-io/kubean/assets/97269208/0bf14337-738c-4e56-8a28-7d9107dbc00e)

**Comment by tu1h** [comment]
What the version of K8s? Maybe it was caused by the incorrect coredns image. See  https://github.com/kubernetes/kubernetes/issues/113543#issuecomment-1780227913
