### ISSUE TITLE
CI failure: In release pipeline, failed at update kubean support matrix

### ISSUE THREAD

**Issue by tu1h** [kubean-io/kubean#987]
Fault spot: https://github.com/kubean-io/kubean/actions/runs/6541730833/job/17764246006

Ref: https://github.com/peter-evans/create-pull-request/issues/707 & https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#filtering-push-events

**Comment by Rei1010** [comment]
Fixed in https://github.com/kubean-io/kubean/pull/1035
