### ISSUE TITLE
copy k8soffline files successfully, but there is "error" message. it is confused

### ISSUE THREAD

**Issue by liyuerich** [kubean-io/kubean#990]
**Describe the version**
version about:
1. kubean 0.8.6

1 generate k8soffline files and image
2 copy files and images to minio(dce 5 internal tinder
3 cd data/v_offline_patch/amd64/files/
 
MINIO_USER=xxx MINIO_PASS=xxx ./import_files.sh http://127.0.0.1:9000 
4 there is error, actually upload is successfully, this is very confused 

...bin/linux/amd64/kubelet: 388.25 MiB / 388.25 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.35 MiB/s 1s
mc: <ERROR> Unable to validate source `offline-files/files.m.daocloud.io`.
...27.0-linux-amd64.tar.gz: 40.15 MiB / 40.15 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.81 MiB/s 0s

**Comment by tu1h** [comment]
I tested for [files-amd64-v0.8.6.tar.gz](https://github.com/kubean-io/kubean/releases/download/v0.8.6/files-amd64-v0.8.6.tar.gz). But I haven't met your issue.
